"""
File        : agents/advancement_agent.py
Triggered By:
    - advancement

Tools:
    - tavily_tool.py
    - groq_tool.py

Input:
    workflow_state["user_input"]
        Original user request or startup idea.

    workflow_state["startup_idea"]
        Normalized startup idea used as the primary advancement context.

    workflow_state["startup_type"]
        Startup industry/category used as broader market context.

Output:
    workflow_state["advancement_plan"] → str
        Structured advancement strategy generated by the LLM.

Responsibilities:
    - Assess the startup's current stage and position.
    - Identify practical opportunities for advancement.
    - Build a concrete and followable scaling roadmap.
    - Suggest a SaaS transformation path when applicable.
    - Recommend enterprise-readiness steps.
    - Research relevant market and scaling benchmarks.
    - Ground advancement recommendations in fresh external evidence.
    - Preserve the normalized startup idea as the foundation.

Execution Flow:
    1. Read startup context.
    2. Build a startup-specific market research query.
    3. Run fresh Tavily market research.
    4. Normalize Tavily results into readable context.
    5. Prepare the advancement system prompt.
    6. Build the advancement analysis prompt.
    7. Prepare the LLM messages.
    8. Generate the advancement plan through Groq.
    9. Store the generated plan in workflow state.
    10. Update pipeline status.
    11. Return the updated workflow state.

Evidence Discipline:
    - STARTUP IDEA is the primary foundation.
    - STARTUP TYPE provides broader industry context.
    - ORIGINAL USER INPUT preserves the user's original intent,
      constraints, and direction.
    - TAVILY MARKET RESEARCH provides fresh external evidence.

Failure Handling:
    Execution logging, timing, retry behavior, and exception handling
    are managed centrally by src/core/decorators.py.
"""

from src.core.decorators import (
    handle_errors,
    log_execution,
    track_timing,
    retry_on_failure
)

from src.prompts.prompts import ADVANCEMENT_PROMPT
from src.tools.tavily_tool import tavily_tool
from src.tools.groq_tool import groq_tool


class AdvancementAgent:
    """
    Determine how an existing startup idea can progress from its
    current stage toward a more scalable, mature, and market-ready
    business.

    AdvancementAgent operates in the advancement workflow.

    The agent combines:
        - Original user input
        - Normalized startup idea
        - Startup industry/category
        - Fresh Tavily market research
        - Advancement strategy defined by the system prompt

    Primary Focus
    -------------
    - Current startup position
    - Practical growth opportunities
    - Scaling strategy
    - SaaS transformation when applicable
    - Enterprise readiness
    - Relevant market and business-model opportunities

    Input State
    -----------
    workflow_state["user_input"]:
        Original startup idea or user request.

    workflow_state["startup_idea"]:
        Normalized startup idea and primary definition of the
        opportunity being evaluated.

    workflow_state["startup_type"]:
        Startup industry/category providing broader market context.

    External Evidence
    -----------------
    Tavily provides fresh market research covering relevant trends,
    customer needs, competitors, business opportunities, growth
    signals, distribution opportunities, and scaling possibilities.

    Output State
    ------------
    workflow_state["advancement_plan"]:
        Structured advancement strategy generated by the LLM.

    workflow_state["pipeline_status"]["AdvancementAgent"]:
        Set to "success" after successful execution.

    Design Principle
    ----------------
    The normalized startup idea remains the foundation of the
    advancement analysis.

    The agent improves and advances the existing opportunity rather
    than replacing it with an unrelated business idea.

    The final advancement plan should be practical, evidence-based,
    and directly connected to the startup's current direction.
    """

    # ============================================================
    # DECORATOR STACK
    # Provides centralized error handling, execution logging,
    # timing measurement, and retry behavior.
    # ============================================================

    @handle_errors
    @log_execution
    @track_timing
    @retry_on_failure
    def run(self, workflow_state: dict) -> dict:
        """
        Generate a practical startup advancement plan.

        Parameters
        ----------
        workflow_state : dict
            Shared workflow state containing the original user input,
            normalized startup context, and pipeline status.

        Returns
        -------
        dict
            Updated workflow state containing the generated
            "advancement_plan" and successful AdvancementAgent status.

        Processing Stages
        -----------------
        1. Read startup context.
        2. Build a startup-specific market research query.
        3. Retrieve fresh evidence through Tavily.
        4. Normalize search results into readable context.
        5. Load the advancement system prompt.
        6. Build the advancement analysis prompt.
        7. Prepare the LLM message payload.
        8. Generate the advancement plan through Groq.
        9. Store the generated plan.
        10. Update pipeline status.
        11. Return the updated workflow state.

        Evidence Handling
        ------------------
        Tavily results provide external evidence for the advancement
        analysis.

        The normalized startup idea remains the primary context, while
        startup type and original user input preserve the category,
        intent, constraints, and direction of the opportunity.
        """

        # ============================================================
        # 1. Read startup context
        # ============================================================

        user_input = workflow_state["user_input"]

        startup_idea = workflow_state["startup_idea"]

        startup_type = workflow_state["startup_type"]

        # ============================================================
        # 2. Build startup-specific market research query
        # ============================================================

        tavily_prompt = f"""
Find recent, credible, directly relevant market evidence and opportunities for this startup.

[STARTUP IDEA]
{startup_idea}

[STARTUP TYPE]
{startup_type}

[ORIGINAL USER INPUT]
{user_input}

[SEARCH PRIORITY]
Use STARTUP IDEA as the primary opportunity signal.
Use STARTUP TYPE for industry/category context.
Use ORIGINAL USER INPUT to preserve the user's specific problem, target customer, constraints, and intended direction.

Search for evidence covering:
- Target customers and unmet needs
- Problem severity and demand
- Competitors and alternatives
- Market and growth opportunities
- Relevant business models
- Distribution and partnership opportunities
- Product/business advancement and scaling opportunities

[QUALITY]
Prefer recent, credible, authoritative, directly relevant sources.
Avoid results that merely mention the same technology, industry, or audience without supporting the actual startup opportunity.

[OUTPUT]
Return relevant sources with original URLs and supporting content.
Preserve URLs exactly; do not invent or modify them.
"""

        # ============================================================
        # 3. Run fresh Tavily market research
        # ============================================================

        tavily_response = tavily_tool.search(
            user_query=tavily_prompt
        )

        # ============================================================
        # 4. Normalize Tavily results into readable context
        # ============================================================

        tavily_context = "\n\n".join(
            f"Source {index}:\n"
            f"URL: {result['url']}\n"
            f"Content: {result['content']}"
            for index, result in enumerate(
                tavily_response,
                start=1
            )
        )

        # ============================================================
        # 5. Prepare advancement system prompt
        # ============================================================

        system_prompt = ADVANCEMENT_PROMPT

        # ============================================================
        # 6. Build advancement analysis prompt
        # ============================================================

        user_prompt = f"""
=== STARTUP IDEA ===
{startup_idea}

=== STARTUP TYPE ===
{startup_type}

=== ORIGINAL USER INPUT ===
{user_input}

=== TAVILY MARKET RESEARCH ===
{tavily_context}

Use STARTUP IDEA as the primary foundation. Use STARTUP TYPE for industry context. Use ORIGINAL USER INPUT to preserve the user's intent and constraints. Use TAVILY MARKET RESEARCH as external evidence.

Identify the strongest practical advancement without replacing the original startup. Support every evidence-based recommendation with relevant Tavily evidence. If evidence is insufficient, mark the recommendation as provisional and requiring validation.

Return only the structured output defined in the system prompt."""

        # ============================================================
        # 7. Prepare LLM messages
        # ============================================================

        messages = [
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_prompt
            }
        ]

        # ============================================================
        # 8. Generate advancement plan
        # ============================================================

        groq_response = groq_tool.generate_text(
            messages=messages
        )

        # ============================================================
        # 9. Store advancement plan in workflow state
        # ============================================================

        workflow_state["advancement_plan"] = (
            groq_response
        )

        # ============================================================
        # 10. Update AdvancementAgent pipeline status
        # ============================================================

        workflow_state["pipeline_status"]["AdvancementAgent"] = (
            "success"
        )

        # ============================================================
        # 11. Return updated workflow state
        # ============================================================

        return workflow_state


# ================================================================
# STANDALONE TEST
# Allows AdvancementAgent to be tested independently using the
# shared mock workflow state.
# ================================================================

if __name__ == "__main__":

    # ============================================================
    # 1. Load mock workflow state
    # ============================================================

    from tests.mock_workflow_state import MOCK_STATE_FULL

    workflow_state = MOCK_STATE_FULL.copy()

    # ============================================================
    # 2. Initialize AdvancementAgent
    # ============================================================

    agent = AdvancementAgent()

    # ============================================================
    # 3. Execute advancement workflow
    # ============================================================

    workflow_state = agent.run(
        workflow_state
    )

    # ============================================================
    # 4. Display generated advancement plan
    # ============================================================

    print(
        workflow_state["advancement_plan"]
    )

    # ============================================================
    # 5. Display execution errors
    # ============================================================

    print(
        workflow_state["errors"]
    )