"""
File        : agents/advancement_agent.py
Triggered By: advancement
Tools       : groq_tool.py + tavily_tool.py

Input:
    workflow_state["user_input"]
        Original startup idea or user request that the agent uses
        as the foundation for evaluating possible advancement paths.

Output:
    workflow_state["advancement_plan"] → str
        Structured plain text with sections:

            ## Current Stage Assessment
            ## Scaling Roadmap
            ## SaaS Transformation Path
            ## Enterprise Readiness Steps
            ## Market Benchmarks

        Each section should be grounded in the market evidence
        retrieved through Tavily.

Responsibilities:
- Assess the startup's current stage and position
- Identify practical opportunities for advancement
- Build a concrete and followable scaling roadmap
- Suggest a SaaS transformation path when applicable
- Recommend enterprise-readiness steps
- Research relevant market and scaling benchmarks
- Ground advancement recommendations in fresh external evidence
- Preserve the user's original startup idea as the foundation
"""


from src.core.decorators import (
    handle_errors,
    log_execution,
    track_timing,
    retry_on_failure
)

from src.prompts.prompts import ADVANCEMENT_PROMPT
from src.tools.tavily_tool import ask_tavily
from src.tools.groq_tool import text_call


class AdvancementAgent:
    """
    Advancement Agent responsible for determining how an existing
    startup idea can move from its current stage toward a more
    scalable, mature, and market-ready business.

    This agent operates in the advancement workflow.

    The agent combines:
        - The user's original startup idea
        - Fresh market research from Tavily
        - The advancement strategy defined by the system prompt

    The agent focuses on:
        - Understanding the startup's current position
        - Identifying practical growth opportunities
        - Defining a realistic scaling path
        - Evaluating whether a SaaS transformation is applicable
        - Identifying enterprise-readiness requirements
        - Comparing the opportunity against relevant market benchmarks

    Input State:
        workflow_state["user_input"]:
            The original startup idea or user request. This remains
            the foundation for the advancement analysis.

    External Evidence:
        Tavily is used to retrieve recent market trends, customer
        needs, competitors, business opportunities, and growth signals
        relevant to the startup.

    Output State:
        workflow_state["advancement_plan"]:
            Structured advancement plan generated by the LLM.

        workflow_state["pipeline_status"]["AdvancementAgent"]:
            Updated to "success" when the agent completes successfully.

    Process:
        1. Read the original startup idea from workflow_state.
        2. Build a startup-specific market research query.
        3. Retrieve fresh evidence using Tavily.
        4. Normalize the search results into readable context.
        5. Provide the startup idea and research context to Groq.
        6. Generate the structured advancement plan.
        7. Store the result in workflow_state.

    Notes:
        The user's original idea is the primary foundation of the
        analysis. Tavily research provides external evidence that
        should help identify realistic growth, scaling, SaaS, and
        enterprise opportunities.

        The advancement plan should be practical and evidence-based
        rather than a generic long-term business roadmap.
    """

    @handle_errors
    @log_execution
    @track_timing
    @retry_on_failure
    def run(self, workflow_state: dict) -> dict:
        """
        Generate a practical startup advancement plan using fresh
        market research.

        Parameters
        ----------
        workflow_state : dict
            Shared state passed between agents in the multi-agent
            workflow.

            Required fields:
                "user_input":
                    Original startup idea or user request that
                    provides the foundation for the analysis.

        Returns
        -------
        dict
            Updated workflow state containing the generated
            advancement plan under "advancement_plan" and the
            updated AdvancementAgent execution status.

        Notes
        -----
        The agent first performs a fresh Tavily search focused on
        market trends, customer needs, competitors, business
        opportunities, and potential growth opportunities relevant
        to the startup.

        The search results are converted into a structured text
        context before being passed to the Groq model.

        The Groq model uses the original startup idea together with
        the external market evidence to generate the required
        advancement plan.

        The generated response is stored directly under
        workflow_state["advancement_plan"].
        """

        # ----------------------------------------------------
        # 1. Read the original startup idea
        # ----------------------------------------------------

        user_input = workflow_state["user_input"]

        # ----------------------------------------------------
        # 2. Build startup-specific market research query
        # ----------------------------------------------------

        tavily_prompt = f"""
Find recent market trends, customer needs, competitors, and business
opportunities directly relevant to this startup:

{user_input}

Focus specifically on the startup's industry, target customers, problem,
and potential growth opportunities.

Return relevant sources with their URLs and supporting content.
Prefer recent, credible, and directly relevant sources.
"""

        # ----------------------------------------------------
        # 3. Run fresh Tavily market research
        # ----------------------------------------------------

        tavily_response = ask_tavily(
            user_query=tavily_prompt
        )

        # ----------------------------------------------------
        # 4. Normalize Tavily results into readable context
        # ----------------------------------------------------

        tavily_context = "\n\n".join(
            f"Source {index}:\n"
            f"URL: {result['url']}\n"
            f"Content: {result['content']}"
            for index, result in enumerate(
                tavily_response,
                start=1
            )
        )

        # ----------------------------------------------------
        # 5. Prepare system prompt
        # ----------------------------------------------------

        system_prompt = ADVANCEMENT_PROMPT

        # ----------------------------------------------------
        # 6. Build advancement analysis prompt
        # ----------------------------------------------------

        user_prompt = f"""
Analyze the user's startup idea using the latest market research below.

=== USER INPUT ===
{user_input}
=== END USER INPUT ===

=== TAVILY MARKET RESEARCH ===
{tavily_context}
=== END TAVILY MARKET RESEARCH ===

Use the user's original idea as the foundation and use the market research as
the primary external evidence.

Identify the strongest practical advancement and return the required
structured output.
"""

        # ----------------------------------------------------
        # 7. Prepare LLM messages
        # ----------------------------------------------------

        messages = [
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_prompt
            }
        ]

        # ----------------------------------------------------
        # 8. Generate advancement plan
        # ----------------------------------------------------

        groq_response = text_call(
            prompt=messages
        )

        # ----------------------------------------------------
        # 9. Store advancement plan in workflow state
        # ----------------------------------------------------

        workflow_state["advancement_plan"] = (
            groq_response
        )

        # ----------------------------------------------------
        # 10. Update pipeline status
        # ----------------------------------------------------

        workflow_state["pipeline_status"]["AdvancementAgent"] = (
            "success"
        )

        # ----------------------------------------------------
        # 11. Return updated workflow state
        # ----------------------------------------------------

        return workflow_state


# ----------------------------------------------------
# LOCAL TEST
# ----------------------------------------------------

if __name__ == "__main__":

    # ----------------------------------------------------
    # 1. Load mock workflow state
    # ----------------------------------------------------

    from tests.mock_workflow_state import MOCK_STATE_FULL

    workflow_state = MOCK_STATE_FULL.copy()

    # ----------------------------------------------------
    # 2. Initialize Advancement Agent
    # ----------------------------------------------------

    agent = AdvancementAgent()

    # ----------------------------------------------------
    # 3. Run advancement pipeline
    # ----------------------------------------------------

    workflow_state = agent.run(
        workflow_state
    )

    # ----------------------------------------------------
    # 4. Print generated advancement plan
    # ----------------------------------------------------

    print(
        workflow_state["advancement_plan"]
    )