"""
File        : agents/general_chat_agent.py
Triggered By: general_chat
Tools       : groq_tool.py

Input:
    workflow_state["user_input"]
        The user's original question or conversational message.

Output:
    workflow_state["chat_response"] → str
        Plain conversational response generated by the LLM.

        Output requirements:
        - Directly answer the user's question
        - Use conversational language
        - No markdown headers
        - No structured report sections
        - No unnecessary formatting

Responsibilities:
- Handle general startup-related questions conversationally
- Provide startup mentoring and guidance
- Answer business-related questions
- Answer funding-related questions
- Answer technology-related questions
- Preserve a conversational response style
- Avoid report-style output for general conversation
"""


from src.core.decorators import (
    handle_errors,
    log_execution,
    track_timing,
    retry_on_failure
)

from src.prompts.prompts import GENERAL_CHAT_PROMPT
from src.tools.groq_tool import text_call


class GeneralChatAgent:
    """
    General Chat Agent responsible for handling conversational user
    requests that do not require a specialized analysis pipeline.

    This agent operates in the general_chat workflow.

    Its purpose is to provide a direct conversational response rather
    than generating a structured startup analysis or report.

    The agent can be used for:
        - Startup-related questions
        - Business questions
        - Funding questions
        - Technology questions
        - General startup mentoring
        - Clarification and guidance

    Input State:
        workflow_state["user_input"]:
            The user's original question or conversational message.

    Output State:
        workflow_state["chat_response"]:
            Plain conversational response generated by the LLM.

        workflow_state["pipeline_status"]["GeneralChatAgent"]:
            Updated to "success" when the agent completes successfully.

    Process:
        1. Read the user's input from workflow_state.
        2. Load the general conversation system prompt.
        3. Build a user prompt containing the user's question.
        4. Send the system and user messages to Groq.
        5. Store the generated response in workflow_state.
        6. Mark the agent execution as successful.

    Notes:
        This agent is intentionally lightweight. It does not perform
        market research, RAG retrieval, scoring, risk analysis, or
        other specialized startup analysis.

        The response should remain conversational and directly address
        the user's question instead of producing a report-style answer.
    """

    @log_execution
    @track_timing
    @retry_on_failure
    @handle_errors
    def run(self, workflow_state: dict) -> dict:
        """
        Generate a direct conversational response to the user's input.

        Parameters
        ----------
        workflow_state : dict
            Shared state passed between agents in the multi-agent workflow.

            Required fields:
                "user_input":
                    The user's question or conversational message.

        Returns
        -------
        dict
            Updated workflow state containing the generated response
            under "chat_response" and the updated GeneralChatAgent
            execution status.

        Notes
        -----
        The user's input is passed to the LLM together with the
        GENERAL_CHAT_PROMPT system instructions.

        The generated response is stored directly under
        workflow_state["chat_response"].

        This agent does not perform additional retrieval or analysis.
        Its responsibility is limited to producing a clear,
        conversational answer.
        """

        # ----------------------------------------------------
        # 1. Read the user's input
        # ----------------------------------------------------

        user_input = workflow_state["user_input"]

        # ----------------------------------------------------
        # 2. Prepare the general conversation system prompt
        # ----------------------------------------------------

        system_prompt = GENERAL_CHAT_PROMPT

        # ----------------------------------------------------
        # 3. Build the user prompt
        # ----------------------------------------------------

        user_prompt = f"""
USER INPUT:
{user_input}

Answer the user's question clearly and directly.
"""

        # ----------------------------------------------------
        # 4. Prepare LLM messages
        # ----------------------------------------------------

        messages = [
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_prompt
            }
        ]

        # ----------------------------------------------------
        # 5. Generate conversational response
        # ----------------------------------------------------

        response = text_call(
            prompt=messages
        )

        # ----------------------------------------------------
        # 6. Store response in workflow state
        # ----------------------------------------------------

        workflow_state["chat_response"] = (
            response
        )

        # ----------------------------------------------------
        # 7. Update pipeline status
        # ----------------------------------------------------

        workflow_state["pipeline_status"]["GeneralChatAgent"] = (
            "success"
        )

        # ----------------------------------------------------
        # 8. Return updated workflow state
        # ----------------------------------------------------

        return workflow_state


# ----------------------------------------------------
# LOCAL TEST
# ----------------------------------------------------

if __name__ == "__main__":

    # ----------------------------------------------------
    # 1. Load mock workflow state
    # ----------------------------------------------------

    from tests.mock_workflow_state import MOCK_STATE_FULL

    workflow_state = MOCK_STATE_FULL.copy()

    # ----------------------------------------------------
    # 2. Initialize General Chat Agent
    # ----------------------------------------------------

    agent = GeneralChatAgent()

    # ----------------------------------------------------
    # 3. Run general conversation pipeline
    # ----------------------------------------------------

    workflow_state = agent.run(
        workflow_state
    )

    # ----------------------------------------------------
    # 4. Print generated conversational response
    # ----------------------------------------------------

    print(
        workflow_state["chat_response"]
    )