"""
File        : agents/general_chat_agent.py
Triggered By:
    - general_chat

Tools:
    - groq_tool.py

Input:
    workflow_state["user_input"]
        Original user question or conversational message.

    workflow_state["startup_idea"]
        Normalized startup idea when available.

    workflow_state["startup_type"]
        Startup industry/category when available.

Output:
    workflow_state["chat_response"] → str
        Plain conversational response generated by the LLM.

        Output requirements:
            - Directly answer the user's question.
            - Use conversational language.
            - Avoid report-style formatting.
            - Avoid unnecessary structured sections.
            - Keep the response relevant to the user's question.

Responsibilities:
    - Handle general startup-related questions conversationally.
    - Provide startup mentoring and guidance.
    - Answer business-related questions.
    - Answer funding-related questions.
    - Answer technology-related questions.
    - Preserve a conversational response style.
    - Use normalized startup context when relevant.
    - Avoid specialized analysis when it is not required.

Execution Flow:
    1. Read the user's input.
    2. Read optional startup context.
    3. Prepare the general conversation system prompt.
    4. Build the conversational user prompt.
    5. Prepare the LLM messages.
    6. Generate the conversational response.
    7. Store the response in workflow state.
    8. Update pipeline status.
    9. Return the updated workflow state.

Context Priority:
    USER INPUT:
        Always the primary conversational signal.

    STARTUP IDEA:
        Supporting context when relevant.

    STARTUP TYPE:
        Supporting industry/category context when relevant.

Failure Handling:
    Execution logging, timing, retry behavior, and exception handling
    are managed centrally by src/core/decorators.py.
"""

from src.core.decorators import (
    handle_errors,
    log_execution,
    track_timing,
    retry_on_failure
)

from src.prompts.prompts import GENERAL_CHAT_PROMPT
from src.tools.groq_tool import groq_tool


class GeneralChatAgent:
    """
    Handle conversational user requests that do not require a
    specialized startup-analysis pipeline.

    GeneralChatAgent operates in the general_chat workflow.

    The agent provides direct conversational responses rather than
    generating structured startup analysis, reports, scores, risks,
    recommendations, or market research.

    Supported Conversation Types
    -----------------------------
    - Startup-related questions
    - Business questions
    - Funding questions
    - Technology questions
    - Startup mentoring
    - Clarification and guidance

    Input State
    -----------
    workflow_state["user_input"]:
        The user's original question or conversational message.

    workflow_state["startup_idea"]:
        Normalized startup idea when available. Used as supporting
        context for relevant startup-related conversations.

    workflow_state["startup_type"]:
        Startup industry/category when available. Used as broader
        context when relevant.

    Output State
    ------------
    workflow_state["chat_response"]:
        Plain conversational response generated by the LLM.

    workflow_state["pipeline_status"]["GeneralChatAgent"]:
        Set to "success" after successful execution.

    Context Principle
    -----------------
    User input always has priority.

    Startup context is supporting information and must not override
    or distract from the user's current question.

    Startup context is optional because general_chat requests may
    occur without a normalized startup idea or startup type.

    Design Principle
    ----------------
    Keep the response conversational, direct, and relevant.

    This agent does not perform:
        - Market research
        - RAG retrieval
        - Startup scoring
        - Risk analysis
        - MVP analysis
        - Competitive analysis
        - Specialized report generation
    """

    # ============================================================
    # DECORATOR STACK
    # Provides centralized execution logging, timing, retry
    # handling, and exception handling.
    # ============================================================

    @handle_errors
    @log_execution
    @track_timing
    @retry_on_failure
    def run(self, workflow_state: dict) -> dict:
        """
        Generate a direct conversational response.

        Parameters
        ----------
        workflow_state : dict
            Shared workflow state containing the user's input and
            optional normalized startup context.

        Returns
        -------
        dict
            Updated workflow state containing the generated
            "chat_response" and successful GeneralChatAgent status.

        Processing Stages
        -----------------
        1. Read the user's input.
        2. Read optional startup context.
        3. Prepare the general conversation system prompt.
        4. Build the conversational user prompt.
        5. Prepare the LLM message payload.
        6. Generate the conversational response.
        7. Store the response in workflow state.
        8. Update pipeline status.
        9. Return the updated workflow state.

        Notes
        -----
        Missing startup context must not prevent general conversation.

        The user's current question remains the primary signal.
        Startup context is injected only as supporting information.
        """

        # ============================================================
        # 1. Read the user's input
        # ============================================================

        user_input = workflow_state["user_input"]

        # ============================================================
        # 2. Read optional startup context
        # ============================================================

        startup_idea = workflow_state.get(
            "startup_idea",
            ""
        )

        startup_type = workflow_state.get(
            "startup_type",
            ""
        )

        # ============================================================
        # 3. Prepare the general conversation system prompt
        # ============================================================

        system_prompt = GENERAL_CHAT_PROMPT

        # ============================================================
        # 4. Build the conversational user prompt
        # ============================================================

        user_prompt = f"""
STARTUP IDEA:
{startup_idea if startup_idea else "Not available"}

STARTUP TYPE:
{startup_type if startup_type else "Not available"}

USER INPUT:
{user_input}

Use the USER INPUT as the primary signal.

Use STARTUP IDEA and STARTUP TYPE only when they are relevant
to the user's current question.

Do not force startup context into unrelated questions.

Answer the user's question clearly and directly.
"""

        # ============================================================
        # 5. Prepare LLM messages
        # ============================================================

        messages = [
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_prompt
            }
        ]

        # ============================================================
        # 6. Generate conversational response
        # ============================================================

        response = groq_tool.generate_text(
            messages=messages
        )

        # ============================================================
        # 7. Store response in workflow state
        # ============================================================

        workflow_state["chat_response"] = (
            response
        )

        # ============================================================
        # 8. Update GeneralChatAgent pipeline status
        # ============================================================

        workflow_state["pipeline_status"]["GeneralChatAgent"] = (
            "success"
        )

        # ============================================================
        # 9. Return updated workflow state
        # ============================================================

        return workflow_state


# ================================================================
# STANDALONE TEST
# Allows GeneralChatAgent to be tested independently using the
# shared mock workflow state.
# ================================================================

if __name__ == "__main__":

    # ============================================================
    # 1. Load mock workflow state
    # ============================================================

    from tests.mock_workflow_state import MOCK_STATE_FULL

    workflow_state = MOCK_STATE_FULL.copy()

    # ============================================================
    # 2. Initialize GeneralChatAgent
    # ============================================================

    agent = GeneralChatAgent()

    # ============================================================
    # 3. Execute general conversation workflow
    # ============================================================

    workflow_state = agent.run(
        workflow_state
    )

    # ============================================================
    # 4. Display generated conversational response
    # ============================================================

    print(
        workflow_state["chat_response"]
    )

    # ============================================================
    # 5. Display execution errors
    # ============================================================

    print(
        workflow_state["errors"]
    )