"""
File        : agents/llm_judge_agent.py
Triggered By:
    - OrchestratorAgent → run_mid()
    - OrchestratorAgent → run_final()

Tools:
    - groq_tool.py

Purpose:
    LLMJudgeAgent is the quality-control layer of the multi-agent
    startup analysis pipeline.

    It evaluates the workflow at two important checkpoints:

    1. MID-PIPELINE JUDGMENT
       Called after Batch 1 + Batch 2 and before the sequential
       analysis agents continue.

       The judge verifies:
           - User input vs classified intent
           - User input vs execution plan
           - Relevance of executed agent outputs
           - Cross-agent output consistency
           - Data sufficiency for downstream analysis

    2. FINAL JUDGMENT
       Called after ReportWriterAgent and before final delivery.

       The judge verifies:
           - Required report structure
           - Source fidelity
           - Unsupported content
           - Internal consistency
           - Citation integrity
           - Startup score consistency
           - Overall report coherence

Input:
    workflow_state : dict
        Shared state produced by the multi-agent workflow.

Output:
    workflow_state["judge_feedback"]["mid_pipeline"]
        Structured judgment from the mid-pipeline checkpoint.

    workflow_state["judge_feedback"]["final"]
        Structured judgment from the final report checkpoint.

Judgment Values:
    PASS
        No material issue was identified.

    WARNING
        The workflow can continue, but a potential issue was detected.

    FAIL
        A material workflow or report problem was identified.

Important:
    The judge is a quality-control component.

    It does NOT:
        - Modify startup analysis
        - Rewrite agent outputs
        - Improve recommendations
        - Generate startup content
        - Automatically fix detected problems

    Its responsibility is to evaluate the supplied evidence and
    record an evidence-based judgment for the orchestrator.
"""


import copy
import json


from src.core.decorators import (
    log_execution,
    track_timing,
    retry_on_failure,
    handle_errors
)


from src.prompts.prompts import (
    LLM_JUDGE_MID_PROMPT,
    LLM_JUDGE_FINAL_PROMPT
)


from src.tools.groq_tool import text_call


class LLMJudgeAgent:
    """
    Quality-control agent responsible for validating the startup
    analysis workflow at two critical checkpoints.

    The LLMJudgeAgent acts as an evaluator rather than a content
    generator. It inspects the information already produced by
    upstream agents and determines whether the workflow has enough
    consistent, relevant, and trustworthy information to continue.

    The agent contains two independent evaluation stages:

        run_mid()
            Performs a mid-pipeline quality check after the first
            major batches of analysis have completed.

            It checks whether:
                - The classified intent matches the user's input.
                - The execution plan is appropriate.
                - Retrieved market and web information is relevant.
                - RAG context is relevant when available.
                - MVP suggestions are supported by available evidence.
                - The workflow contains sufficient information for
                  downstream analysis.

        run_final()
            Performs the final quality audit after ReportWriterAgent.

            It checks whether:
                - The final report follows the required structure.
                - Report claims remain faithful to source data.
                - Unsupported information has not been introduced.
                - Different sections remain internally consistent.
                - Citations and source URLs remain intact.
                - The startup score matches the upstream analysis.
                - The final report is coherent and evidence-based.

    Input State:
        workflow_state:
            Shared state containing the outputs generated by the
            multi-agent pipeline.

    Output State:
        workflow_state["judge_feedback"]["mid_pipeline"]:
            Result produced by run_mid().

        workflow_state["judge_feedback"]["final"]:
            Result produced by run_final().

        workflow_state["pipeline_status"]["LLMJudgeAgent"]:
            Stores the execution status of each judge checkpoint.

    Important:
        This agent does not alter the actual startup analysis.

        Its role is to provide a structured quality signal that the
        orchestrator can use to understand whether the pipeline output
        is acceptable, potentially problematic, or invalid.
    """


    # ==============================================================
    # MID JUDGE RESPONSE FORMAT
    # ==============================================================

    MID_RESPONSE_FORMAT = {
        "type": "json_schema",
        "json_schema": {
            "name": "llm_judge_mid",
            "strict": True,
            "schema": {
                "type": "object",
                "properties": {
                    "judgment": {
                        "type": "string",
                        "enum": [
                            "PASS",
                            "WARNING",
                            "FAIL"
                        ]
                    },
                    "reason": {
                        "type": "string",
                        "description": (
                            "Concise evidence-based explanation of the judgment. "
                            "Do not introduce information not present in the input."
                        )
                    },
                    "issues": {
                        "type": "array",
                        "description": (
                            "Specific evidence-supported workflow problems. "
                            "Must be empty when judgment is PASS."
                        ),
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "required": [
                    "judgment",
                    "reason",
                    "issues"
                ],
                "additionalProperties": False
            }
        }
    }


    # ==============================================================
    # FINAL JUDGE RESPONSE FORMAT
    # ==============================================================

    FINAL_RESPONSE_FORMAT = {
        "type": "json_schema",
        "json_schema": {
            "name": "llm_judge_final",
            "strict": True,
            "schema": {
                "type": "object",
                "properties": {
                    "judgment": {
                        "type": "string",
                        "enum": [
                            "PASS",
                            "WARNING",
                            "FAIL"
                        ]
                    },
                    "reason": {
                        "type": "string",
                        "description": (
                            "Concise evidence-based explanation of the final "
                            "report judgment."
                        )
                    },
                    "issues": {
                        "type": "array",
                        "description": (
                            "Specific evidence-supported problems detected "
                            "in the final report. Empty when judgment is PASS."
                        ),
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "required": [
                    "judgment",
                    "reason",
                    "issues"
                ],
                "additionalProperties": False
            }
        }
    }


    # ==============================================================
    # MID-PIPELINE JUDGE
    # ==============================================================

    @log_execution
    @track_timing
    @retry_on_failure
    @handle_errors
    def run_mid(self, workflow_state: dict) -> dict:
        """
        Perform the mid-pipeline quality check.

        This checkpoint evaluates the workflow after Batch 1 and
        Batch 2 have completed, before the pipeline moves into the
        sequential analysis stages.

        Parameters
        ----------
        workflow_state : dict
            Shared workflow state containing the user's input,
            classified intent, execution plan, research outputs,
            RAG context, and MVP suggestions.

        Reads
        -----
        user_input:
            Original user request.

        intent:
            Intent selected by IntentRouterAgent.

        execution_plan:
            Agent execution plan selected for the current intent.

        market_data:
            Market research produced by upstream research agents.

        web_search_results:
            External web research produced by WebSearchAgent.

        rag_context:
            Relevant pitch-deck or document context when available.

        mvp_suggestions:
            MVP recommendations produced by MVPAdvisorAgent.

        Writes
        ------
        workflow_state["judge_feedback"]["mid_pipeline"]:
            Structured PASS, WARNING, or FAIL judgment containing
            an evidence-based reason and detected issues.

        workflow_state["pipeline_status"]["LLMJudgeAgent"]["run_mid"]:
            Set to "success" after successful evaluation.

        Returns
        -------
        dict
            Updated workflow state containing the mid-pipeline
            quality judgment.

        Notes
        -----
        The judge only evaluates the supplied workflow data.

        It does not modify the underlying agent outputs or attempt
        to repair problems detected during this checkpoint.
        """

        # ----------------------------------------------------------
        # STAGE 1 — READ REQUIRED WORKFLOW STATE
        # ----------------------------------------------------------

        user_input = workflow_state["user_input"]

        intent = workflow_state["intent"]

        execution_plan = workflow_state["execution_plan"]

        market_data = workflow_state["market_data"]

        web_search_results = workflow_state["web_search_results"]

        rag_context = workflow_state["rag_context"]

        mvp_suggestions = workflow_state["mvp_suggestions"]


        # ----------------------------------------------------------
        # STAGE 2 — NORMALIZE STRUCTURED WORKFLOW DATA
        # ----------------------------------------------------------

        execution_plan = self._to_prompt_string(
            execution_plan
        )

        rag_context = self._to_prompt_string(
            rag_context
        )


        # ----------------------------------------------------------
        # STAGE 3 — BUILD MID-PIPELINE EVALUATION PROMPT
        # ----------------------------------------------------------

        mid_user_prompt = f"""
Evaluate the current workflow using only the supplied data.

==============================
USER INPUT
==============================
{user_input}

==============================
CLASSIFIED INTENT
==============================
{intent}

==============================
EXECUTION PLAN
==============================
{execution_plan}

==============================
MARKET DATA
==============================
{market_data}

==============================
WEB SEARCH RESULTS
==============================
{web_search_results}

==============================
RAG CONTEXT
==============================
{rag_context}

==============================
MVP SUGGESTIONS
==============================
{mvp_suggestions}

==============================
END OF WORKFLOW DATA
==============================
"""


        # ----------------------------------------------------------
        # STAGE 4 — PREPARE STRUCTURED LLM MESSAGES
        # ----------------------------------------------------------

        messages = [
            {
                "role": "system",
                "content": LLM_JUDGE_MID_PROMPT
            },
            {
                "role": "user",
                "content": mid_user_prompt
            }
        ]


        # ----------------------------------------------------------
        # STAGE 5 — RUN GROQ STRUCTURED JUDGMENT
        # ----------------------------------------------------------

        response = text_call(
            messages=messages,
            temperature=0.0,
            response_format=self.MID_RESPONSE_FORMAT,
            reasoning_effort="high",
            include_reasoning=False
        )


        # ----------------------------------------------------------
        # STAGE 6 — PARSE STRICT JSON RESPONSE
        # ----------------------------------------------------------

        judge_result = json.loads(
            response
        )


        # ----------------------------------------------------------
        # STAGE 7 — STORE MID-PIPELINE JUDGMENT
        # ----------------------------------------------------------

        workflow_state["judge_feedback"]["mid_pipeline"] = (
            judge_result
        )


        # ----------------------------------------------------------
        # STAGE 8 — UPDATE MID-JUDGE PIPELINE STATUS
        # ----------------------------------------------------------

        workflow_state["pipeline_status"].setdefault(
            "LLMJudgeAgent",
            {}
        )

        workflow_state["pipeline_status"]["LLMJudgeAgent"]["run_mid"] = (
            "success"
        )


        # ----------------------------------------------------------
        # STAGE 9 — RETURN UPDATED WORKFLOW STATE
        # ----------------------------------------------------------

        return workflow_state


    # ==============================================================
    # FINAL JUDGE
    # ==============================================================

    @log_execution
    @track_timing
    @retry_on_failure
    @handle_errors
    def run_final(self, workflow_state: dict) -> dict:
        """
        Perform the final quality audit of the generated startup report.

        This checkpoint runs after ReportWriterAgent and before the
        final result is delivered to the user.

        Parameters
        ----------
        workflow_state : dict
            Shared workflow state containing the final report and
            the upstream evidence used to generate that report.

        Reads
        -----
        final_report:
            Final Markdown report generated by ReportWriterAgent.

        user_input:
            Original startup idea or user request.

        pitch_deck_text:
            Original pitch-deck information when provided.

        judge_feedback:
            Previous judge feedback available in the workflow.

        market_data:
            Market research evidence.

        web_search_results:
            External web research evidence.

        rag_context:
            Relevant retrieved pitch-deck or document context.

        mvp_suggestions:
            MVP recommendations.

        tech_recommendations:
            Technology recommendations.

        risk_analysis:
            Risk analysis.

        startup_score:
            Startup viability score and breakdown.

        recommendations:
            Improvement recommendations.

        generated_ideas:
            Generated startup ideas when available.

        nurtured_idea:
            Refined startup concept when available.

        advancement_plan:
            Startup advancement strategy when available.

        Writes
        ------
        workflow_state["judge_feedback"]["final"]:
            Structured PASS, WARNING, or FAIL judgment for the
            final startup report.

        workflow_state["pipeline_status"]["LLMJudgeAgent"]["run_final"]:
            Set to "success" after successful final evaluation.

        Returns
        -------
        dict
            Updated workflow state containing the final quality judgment.

        Notes
        -----
        The final judge compares the report against the source
        workflow data.

        It checks source fidelity and consistency rather than
        generating a replacement report.

        The final judgment is intended to catch unsupported claims,
        missing sections, citation problems, contradictory scores,
        and other report-level quality issues before delivery.
        """

        # ----------------------------------------------------------
        # STAGE 1 — READ FINAL REPORT AND SOURCE WORKFLOW DATA
        # ----------------------------------------------------------

        final_report = workflow_state["final_report"]

        user_input = workflow_state["user_input"]

        pitch_deck_text = workflow_state["pitch_deck_text"]

        judge_feedback = workflow_state["judge_feedback"]

        market_data = workflow_state["market_data"]

        web_search_results = workflow_state["web_search_results"]

        rag_context = workflow_state["rag_context"]

        mvp_suggestions = workflow_state["mvp_suggestions"]

        tech_recommendations = workflow_state["tech_recommendations"]

        risk_analysis = workflow_state["risk_analysis"]

        startup_score = workflow_state["startup_score"]

        recommendations = workflow_state["recommendations"]

        generated_ideas = workflow_state["generated_ideas"]

        nurtured_idea = workflow_state["nurtured_idea"]

        advancement_plan = workflow_state["advancement_plan"]


        # ----------------------------------------------------------
        # STAGE 2 — NORMALIZE STRUCTURED WORKFLOW DATA
        # ----------------------------------------------------------

        pitch_deck_text = self._to_prompt_string(
            pitch_deck_text
        )

        judge_feedback = self._to_prompt_string(
            judge_feedback
        )

        rag_context = self._to_prompt_string(
            rag_context
        )

        startup_score = self._to_prompt_string(
            startup_score
        )

        recommendations = self._to_prompt_string(
            recommendations
        )

        generated_ideas = self._to_prompt_string(
            generated_ideas
        )


        # ----------------------------------------------------------
        # STAGE 3 — BUILD FINAL REPORT AUDIT PROMPT
        # ----------------------------------------------------------

        final_user_prompt = f"""
Audit the final report against the supplied workflow source data.

Use only the information provided below.

==============================
FINAL REPORT
==============================
{final_report}

==============================
USER INPUT
==============================
{user_input}

==============================
PITCH DECK TEXT
==============================
{pitch_deck_text}

==============================
JUDGE FEEDBACK
==============================
{judge_feedback}

==============================
MARKET DATA
==============================
{market_data}

==============================
WEB SEARCH RESULTS
==============================
{web_search_results}

==============================
RAG CONTEXT
==============================
{rag_context}

==============================
MVP SUGGESTIONS
==============================
{mvp_suggestions}

==============================
TECH RECOMMENDATIONS
==============================
{tech_recommendations}

==============================
RISK ANALYSIS
==============================
{risk_analysis}

==============================
STARTUP SCORE
==============================
{startup_score}

==============================
RECOMMENDATIONS
==============================
{recommendations}

==============================
GENERATED IDEAS
==============================
{generated_ideas}

==============================
NURTURED IDEA
==============================
{nurtured_idea}

==============================
ADVANCEMENT PLAN
==============================
{advancement_plan}

==============================
END SOURCE DATA
==============================
"""


        # ----------------------------------------------------------
        # STAGE 4 — PREPARE STRUCTURED LLM MESSAGES
        # ----------------------------------------------------------

        messages = [
            {
                "role": "system",
                "content": LLM_JUDGE_FINAL_PROMPT
            },
            {
                "role": "user",
                "content": final_user_prompt
            }
        ]


        # ----------------------------------------------------------
        # STAGE 5 — RUN GROQ STRUCTURED FINAL JUDGMENT
        # ----------------------------------------------------------

        response = text_call(
            messages=messages,
            temperature=0.0,
            response_format=self.FINAL_RESPONSE_FORMAT,
            reasoning_effort="high",
            include_reasoning=False
        )


        # ----------------------------------------------------------
        # STAGE 6 — PARSE STRICT JSON RESPONSE
        # ----------------------------------------------------------

        judge_result = json.loads(
            response
        )


        # ----------------------------------------------------------
        # STAGE 7 — STORE FINAL JUDGMENT
        # ----------------------------------------------------------

        workflow_state["judge_feedback"]["final"] = (
            judge_result
        )


        # ----------------------------------------------------------
        # STAGE 8 — UPDATE FINAL-JUDGE PIPELINE STATUS
        # ----------------------------------------------------------

        workflow_state["pipeline_status"].setdefault(
            "LLMJudgeAgent",
            {}
        )

        workflow_state["pipeline_status"]["LLMJudgeAgent"]["run_final"] = (
            "success"
        )


        # ----------------------------------------------------------
        # STAGE 9 — RETURN UPDATED WORKFLOW STATE
        # ----------------------------------------------------------

        return workflow_state


    # ==============================================================
    # PROMPT DATA NORMALIZATION
    # ==============================================================

    @staticmethod
    def _to_prompt_string(value) -> str:
        """
        Convert structured workflow data into a readable prompt string.

        Parameters
        ----------
        value :
            Workflow data that may be a dictionary, list, string,
            or primitive value.

        Returns
        -------
        str
            JSON-formatted text for dictionaries and lists, or a
            standard string representation for other values.

        Notes
        -----
        JSON formatting is used for dictionaries and lists so that
        nested workflow structures remain readable to the LLM.

        The helper does not modify the original workflow data.
        """

        # ----------------------------------------------------------
        # Convert dictionaries and lists into readable JSON
        # ----------------------------------------------------------

        if isinstance(value, (dict, list)):
            return json.dumps(
                value,
                indent=2,
                ensure_ascii=False,
                default=str
            )

        # ----------------------------------------------------------
        # Convert primitive values directly to strings
        # ----------------------------------------------------------

        return str(value)


# ==============================================================
# STANDALONE TEST
# ==============================================================

if __name__ == "__main__":

    # ----------------------------------------------------------
    # 1. Load shared mock workflow state
    # ----------------------------------------------------------

    from tests.mock_workflow_state import MOCK_STATE_FULL

    # ----------------------------------------------------------
    # 2. Initialize LLM Judge Agent
    # ----------------------------------------------------------

    agent = LLMJudgeAgent()


    # ==========================================================
    # MID-PIPELINE JUDGE TEST
    # ==========================================================

    # ----------------------------------------------------------
    # 3. Create isolated state for mid-pipeline evaluation
    # ----------------------------------------------------------

    workflow_state_mid = copy.deepcopy(
        MOCK_STATE_FULL
    )

    # ----------------------------------------------------------
    # 4. Run mid-pipeline quality check
    # ----------------------------------------------------------

    workflow_state_mid = agent.run_mid(
        workflow_state_mid
    )

    # ----------------------------------------------------------
    # 5. Display mid-pipeline judgment
    # ----------------------------------------------------------

    print(
        "\nMID-PIPELINE JUDGE:\n"
    )

    print(
        workflow_state_mid["judge_feedback"]["mid_pipeline"]
    )


    # ==========================================================
    # FINAL JUDGE TEST
    # ==========================================================

    # ----------------------------------------------------------
    # 6. Create isolated state for final evaluation
    # ----------------------------------------------------------

    workflow_state_final = copy.deepcopy(
        MOCK_STATE_FULL
    )

    # ----------------------------------------------------------
    # 7. Run final report quality audit
    # ----------------------------------------------------------

    workflow_state_final = agent.run_final(
        workflow_state_final
    )

    # ----------------------------------------------------------
    # 8. Display final judgment
    # ----------------------------------------------------------

    print(
        "\nFINAL JUDGE:\n"
    )

    print(
        workflow_state_final["judge_feedback"]["final"]
    )