"""
File        : agents/llm_judge_agent.py
Triggered By:
    - OrchestratorAgent → run_mid()
    - OrchestratorAgent → run_final()

Tools:
    # Claude: prev -> - groq_tool.py
    # Phase 5 migrated both checkpoints to Gemini.
    - gemini_tool.py

Purpose:
    LLMJudgeAgent is the quality-control layer of the BizRadar
    multi-agent startup analysis pipeline.

    It evaluates workflow quality at two checkpoints:

    1. MID-PIPELINE JUDGMENT
       Runs after the initial research and MVP analysis batches.
       It validates whether the workflow is sufficiently relevant,
       consistent, and complete before sequential analysis continues.

    2. FINAL JUDGMENT
       Runs after ReportWriterAgent.
       It validates the final report before delivery.

MID-PIPELINE CHECKS:
    - User input vs classified intent
    - User input vs execution plan
    - Relevance of upstream research
    - RAG context relevance when available
    - MVP recommendation support
    - Cross-agent consistency
    - Data sufficiency for downstream analysis

FINAL CHECKS:
    - Required report structure
    - Source fidelity
    - Unsupported claims
    - Internal consistency
    - Citation integrity
    - Startup score consistency
    - Overall report quality

Input:
    workflow_state : dict
        Shared workflow state containing the outputs generated by
        upstream agents.

Output:
    workflow_state["judge_feedback"]["mid_pipeline"]
        Structured judgment from the mid-pipeline checkpoint.

    workflow_state["judge_feedback"]["final"]
        Structured judgment from the final report checkpoint.

    workflow_state["pipeline_status"]["LLMJudgeAgent"]
        Execution status for each judge checkpoint.

Judgment Values:
    PASS
        No material issue identified.

    WARNING
        A potential issue was detected, but the pipeline may continue.

    FAIL
        A material workflow or report-level problem was identified.

Important:
    LLMJudgeAgent is an evaluator, not a corrective agent.

    It does NOT:
        - Modify startup analysis
        - Rewrite agent outputs
        - Generate recommendations
        - Generate startup content
        - Automatically repair detected problems

    Its responsibility is to evaluate the supplied workflow data and
    record an evidence-based quality judgment for the orchestrator.
"""


import copy
import json


from src.core.decorators import (
    log_execution,
    track_timing,
    retry_on_failure,
    handle_errors
)


from src.prompts.prompts import (
    LLM_JUDGE_MID_PROMPT,
    LLM_JUDGE_FINAL_PROMPT
)


from src.tools.gemini_tool import gemini_tool


class LLMJudgeAgent:
    """
    Quality-control agent responsible for evaluating BizRadar workflow
    output at the mid-pipeline and final-report checkpoints.

    The agent acts strictly as an evaluator. It consumes information
    already produced by upstream agents and returns a structured
    judgment without modifying the underlying analysis.

    Evaluation Stages
    -----------------
    run_mid()
        Evaluates the workflow after the initial research and MVP
        batches have completed.

        Checks:
            - Intent alignment
            - Execution-plan alignment
            - Market and web research relevance
            - RAG relevance when available
            - MVP evidence support
            - Cross-agent consistency
            - Data sufficiency

    run_final()
        Evaluates the final report after ReportWriterAgent.

        Checks:
            - Report structure
            - Source fidelity
            - Unsupported claims
            - Internal consistency
            - Citation integrity
            - Startup score consistency
            - Overall report coherence

    Input State
    -----------
    workflow_state:
        Shared state containing startup context, research results,
        agent outputs, and generated report information.

    Output State
    ------------
    workflow_state["judge_feedback"]["mid_pipeline"]:
        Structured result from run_mid().

    workflow_state["judge_feedback"]["final"]:
        Structured result from run_final().

    workflow_state["pipeline_status"]["LLMJudgeAgent"]:
        Execution status for the judge checkpoints.

    Design Principle
    ----------------
    The judge identifies problems; it does not fix them.

    The orchestrator decides how the pipeline should proceed after
    receiving the judgment.
    """


    # ==============================================================
    # MID JUDGE RESPONSE FORMAT
    # ==============================================================

    MID_RESPONSE_FORMAT = {
        "type": "object",
        "properties": {
            "judgment": {
                "type": "string",
                "enum": [
                    "PASS",
                    "WARNING",
                    "FAIL"
                ]
            },
            "reason": {
                "type": "string",
                "description": (
                    "Concise evidence-based explanation of the judgment. "
                    "Do not introduce information not present in the input."
                )
            },
            "issues": {
                "type": "array",
                "description": (
                    "Specific evidence-supported workflow problems. "
                    "Must be empty when judgment is PASS."
                ),
                "items": {
                    "type": "string"
                }
            }
        },
        "required": [
            "judgment",
            "reason",
            "issues"
        ]
    }


    # ==============================================================
    # FINAL JUDGE RESPONSE FORMAT
    # ==============================================================

    FINAL_RESPONSE_FORMAT = {
        "type": "object",
        "properties": {
            "judgment": {
                "type": "string",
                "enum": [
                    "PASS",
                    "WARNING",
                    "FAIL"
                ]
            },
            "reason": {
                "type": "string",
                "description": (
                    "Concise evidence-based explanation of the final "
                    "report judgment."
                )
            },
            "issues": {
                "type": "array",
                "description": (
                    "Specific evidence-supported problems detected "
                    "in the final report. Empty when judgment is PASS."
                ),
                "items": {
                    "type": "string"
                }
            }
        },
        "required": [
            "judgment",
            "reason",
            "issues"
        ]
    }


    # ==============================================================
    # MID-PIPELINE JUDGE
    # ==============================================================

    @handle_errors
    @log_execution
    @track_timing
    @retry_on_failure
    def run_mid(self, workflow_state: dict) -> dict:
        """
        Evaluate workflow quality at the mid-pipeline checkpoint.

        Parameters
        ----------
        workflow_state : dict
            Shared workflow state containing:
                - User input
                - Startup context
                - Classified intent
                - Execution plan
                - Market research
                - Web search results
                - RAG context
                - MVP suggestions

        Returns
        -------
        dict
            Updated workflow state containing the structured mid-pipeline
            judgment under:
            workflow_state["judge_feedback"]["mid_pipeline"]

        Processing Stages
        -----------------
        1. Read required workflow state.
        2. Normalize structured values for prompt construction.
        3. Build the mid-pipeline audit prompt.
        4. Prepare structured LLM messages.
        5. Execute the Groq judge call.
        6. Parse the strict JSON response.
        7. Store the judgment in workflow state.
        8. Update the judge pipeline status.
        9. Return the updated workflow state.

        Notes
        -----
        The judge evaluates only the supplied workflow information.
        It does not modify or repair upstream agent outputs.
        """

        # ============================================================
        # 1. Read required workflow state
        # ============================================================

        user_input = workflow_state["user_input"]

        startup_idea = workflow_state["startup_idea"]
        
        startup_type = workflow_state["startup_type"]
        
        intent = workflow_state["intent"]

        execution_plan = workflow_state["execution_plan"]

        market_data = workflow_state["market_data"]

        web_search_results = workflow_state["web_search_results"]

        rag_context = workflow_state["rag_context"]

        mvp_suggestions = workflow_state["mvp_suggestions"]


        # ============================================================
        # 2. Normalize structured workflow data
        # ============================================================

        execution_plan = self._to_prompt_string(
            execution_plan
        )

        rag_context = self._to_prompt_string(
            rag_context
        )


        # ============================================================
        # 3. Build evaluation prompt
        # ============================================================

        mid_user_prompt = f"""
Evaluate the current workflow using only the supplied data.

USER INPUT:
{user_input}

STARTUP IDEA:
{startup_idea}

STARTUP TYPE:
{startup_type}

CLASSIFIED INTENT:
{intent}

EXECUTION PLAN:
{execution_plan}

MARKET DATA:
{market_data}

WEB SEARCH RESULTS:
{web_search_results}

RAG CONTEXT:
{rag_context}

MVP SUGGESTIONS:
{mvp_suggestions}
"""


        # ============================================================
        # 4. Prepare structured LLM messages
        # ============================================================

        messages = (
            LLM_JUDGE_MID_PROMPT +
            "\n\n" +
            mid_user_prompt
        )


        # ============================================================
        # 5. Execute Groq structured judgment
        # ============================================================

        response = gemini_tool.generate_text(
            user_prompt=messages,
            gemini_model="gemini-3.6-flash",
            json_mode=True,
            response_schema=self.MID_RESPONSE_FORMAT,
        )


        # ============================================================
        # 6. Parse structured JSON response
        # ============================================================

        judge_result = json.loads(
            response
        )


        # ============================================================
        # 7. Store judgment in workflow state
        # ============================================================

        workflow_state["judge_feedback"]["mid_pipeline"] = (
            judge_result
        )


        # ============================================================
        # 8. Update LLMJudgeAgent pipeline status
        # ============================================================

        # Claude: prev -> LLMJudgeAgent was the ONLY agent writing a nested
        # dict into pipeline_status, while the other 16 agents, the
        # orchestrator, and handle_errors all write a flat string:
        #
        #     workflow_state["pipeline_status"].setdefault(
        #         "LLMJudgeAgent",
        #         {}
        #     )
        #
        #     workflow_state["pipeline_status"]["LLMJudgeAgent"]["run_mid"] = (
        #         "success"
        #     )
        #
        # Two incompatible shapes on one key meant order decided the
        # outcome: a flat write first made setdefault return a str and the
        # subscript assignment raised "TypeError: 'str' object does not
        # support item assignment"; a nested write first was silently
        # destroyed by the next flat write.
        #
        # Claude: now -> flat key, matching every other writer.
        workflow_state["pipeline_status"]["LLMJudgeAgent.run_mid"] = (
            "success"
        )


        # ============================================================
        # 9. Return updated workflow state
        # ============================================================
        
        return workflow_state


    # ==============================================================
    # FINAL JUDGE
    # ==============================================================
    
    @handle_errors
    @log_execution
    @track_timing
    @retry_on_failure
    def run_final(self, workflow_state: dict) -> dict:
        """
        Perform the final quality audit of the generated startup report.

        Parameters
        ----------
        workflow_state : dict
            Shared workflow state containing the final report and the
            upstream evidence used to produce it.

        Returns
        -------
        dict
            Updated workflow state containing the structured final judgment
            under:
            workflow_state["judge_feedback"]["final"]

        Processing Stages
        -----------------
        1. Read the final report and source workflow data.
        2. Normalize structured values for prompt construction.
        3. Build the final report audit prompt.
        4. Prepare structured LLM messages.
        5. Execute the Groq judge call.
        6. Parse the strict JSON response.
        7. Store the final judgment.
        8. Update the judge pipeline status.
        9. Return the updated workflow state.

        Notes
        -----
        The final judge compares the generated report against the supplied
        workflow evidence.

        It identifies unsupported claims, missing information,
        inconsistencies, citation problems, and other quality issues.
        It does not generate or rewrite the report.
        """

        # ============================================================
        # 1. Read required workflow state
        # ============================================================

        final_report = workflow_state["final_report"]

        user_input = workflow_state["user_input"]

        startup_idea = workflow_state["startup_idea"]
        
        startup_type = workflow_state["startup_type"]

        pitch_deck_text = workflow_state["pitch_deck_text"]

        judge_feedback = workflow_state["judge_feedback"]

        market_data = workflow_state["market_data"]

        web_search_results = workflow_state["web_search_results"]

        rag_context = workflow_state["rag_context"]

        mvp_suggestions = workflow_state["mvp_suggestions"]

        tech_recommendations = workflow_state["tech_recommendations"]

        risk_analysis = workflow_state["risk_analysis"]

        startup_score = workflow_state["startup_score"]

        recommendations = workflow_state["recommendations"]

        generated_ideas = workflow_state["generated_ideas"]

        nurtured_idea = workflow_state["nurtured_idea"]

        advancement_plan = workflow_state["advancement_plan"]


        # ============================================================
        # 2. Normalize structured workflow data
        # ============================================================

        pitch_deck_text = self._to_prompt_string(
            pitch_deck_text
        )

        judge_feedback = self._to_prompt_string(
            judge_feedback
        )

        rag_context = self._to_prompt_string(
            rag_context
        )

        startup_score = self._to_prompt_string(
            startup_score
        )

        recommendations = self._to_prompt_string(
            recommendations
        )

        generated_ideas = self._to_prompt_string(
            generated_ideas
        )


        # ============================================================
        # 3. Build evaluation prompt
        # ============================================================

        final_user_prompt = f"""
Audit the final report against the supplied workflow source data. Use only the information provided below.

FINAL REPORT:
{final_report}

USER INPUT:
{user_input}

STARTUP IDEA:
{startup_idea}

STARTUP TYPE:
{startup_type}

PITCH DECK TEXT:
{pitch_deck_text}

JUDGE FEEDBACK:
{judge_feedback}

MARKET DATA:
{market_data}

WEB SEARCH RESULTS:
{web_search_results}

RAG CONTEXT:
{rag_context}

MVP SUGGESTIONS:
{mvp_suggestions}

TECH RECOMMENDATIONS:
{tech_recommendations}

RISK ANALYSIS:
{risk_analysis}

STARTUP SCORE:
{startup_score}

RECOMMENDATIONS:
{recommendations}

GENERATED IDEAS:
{generated_ideas}

NURTURED IDEA:
{nurtured_idea}

ADVANCEMENT PLAN:
{advancement_plan}
"""


        # ============================================================
        # 4. Prepare structured LLM messages
        # ============================================================

        messages = (
            LLM_JUDGE_FINAL_PROMPT +
            "\n\n" +
            final_user_prompt
        )
    


        # ============================================================
        # 5. Execute Groq structured judgment
        # ============================================================

        response = gemini_tool.generate_text(
            user_prompt=messages,
            gemini_model="gemini-3.6-flash",
            json_mode=True,
            response_schema=self.FINAL_RESPONSE_FORMAT,
        )


        # ============================================================
        # 6. Parse structured JSON response
        # ============================================================

        judge_result = json.loads(
            response
        )


        # ============================================================
        # 7. Store judgment in workflow state
        # ============================================================

        workflow_state["judge_feedback"]["final"] = (
            judge_result
        )


        # ============================================================
        # 8. Update LLMJudgeAgent pipeline status
        # ============================================================

        # Claude: prev -> nested dict write, same incompatible shape as the
        # run_mid checkpoint above:
        #
        #     workflow_state["pipeline_status"].setdefault(
        #         "LLMJudgeAgent",
        #         {}
        #     )
        #
        #     workflow_state["pipeline_status"]["LLMJudgeAgent"]["run_final"] = (
        #         "success"
        #     )
        #
        # Claude: now -> flat key, matching every other writer.
        workflow_state["pipeline_status"]["LLMJudgeAgent.run_final"] = (
            "success"
        )


        # ============================================================
        # 9. Return updated workflow state
        # ============================================================

        return workflow_state


    # ==============================================================
    # PROMPT DATA NORMALIZATION
    # ==============================================================

    @staticmethod
    def _to_prompt_string(value) -> str:
        """
        Convert workflow data into a prompt-readable string.

        Parameters
        ----------
        value :
            Dictionary, list, string, or primitive workflow value.

        Returns
        -------
        str
            JSON-formatted text for dictionaries and lists, or a standard
            string representation for primitive values.

        Notes
        -----
        Dictionaries and lists are formatted as indented JSON so nested
        workflow structures remain readable during LLM evaluation.

        The original workflow-state value is not modified.
        """

        # ----------------------------------------------------------
        # Convert dictionaries and lists into readable JSON
        # ----------------------------------------------------------

        if isinstance(value, (dict, list)):
            return json.dumps(
                value,
                indent=2,
                ensure_ascii=False,
                default=str
            )

        # ----------------------------------------------------------
        # Convert primitive values directly to strings
        # ----------------------------------------------------------

        return str(value)


# ==============================================================
# STANDALONE TEST
# ==============================================================

if __name__ == "__main__":

    # ----------------------------------------------------------
    # 1. Load shared mock workflow state
    # ----------------------------------------------------------

    from tests.mock_workflow_state import MOCK_STATE_FULL

    # ----------------------------------------------------------
    # 2. Initialize LLM Judge Agent
    # ----------------------------------------------------------

    agent = LLMJudgeAgent()


    # ==========================================================
    # MID-PIPELINE JUDGE TEST
    # ==========================================================

    # ----------------------------------------------------------
    # 3. Create isolated state for mid-pipeline evaluation
    # ----------------------------------------------------------

    workflow_state_mid = copy.deepcopy(
        MOCK_STATE_FULL
    )

    # ----------------------------------------------------------
    # 4. Run mid-pipeline quality check
    # ----------------------------------------------------------

    result_mid = agent.run_mid(
        workflow_state_mid
    )

    # ----------------------------------------------------------
    # 5. Display mid-pipeline judgment
    # ----------------------------------------------------------

    print(
        "\nMID-PIPELINE JUDGE:\n"
    )

    print("RETURN TYPE:", type(result_mid))
    print("RETURN VALUE:", result_mid["judge_feedback"]["mid_pipeline"])
    print("ERRORS:", workflow_state_mid["errors"])
    print(result_mid["judge_feedback"])

    # ==========================================================
    # FINAL JUDGE TEST
    # ==========================================================

    # ----------------------------------------------------------
    # 6. Create isolated state for final evaluation
    # ----------------------------------------------------------

    workflow_state_final = copy.deepcopy(
        MOCK_STATE_FULL
    )

    # ----------------------------------------------------------
    # 7. Run final report quality audit
    # ----------------------------------------------------------

    result_final = agent.run_final(
        workflow_state_final
    )

    # ----------------------------------------------------------
    # 8. Display final judgment
    # ----------------------------------------------------------

    print(
        "\nFINAL JUDGE:\n"
    )

    print("RETURN TYPE:", type(result_final))
    print("RETURN VALUE:", result_final["judge_feedback"]["final"])
    print("ERRORS:", workflow_state_final["errors"])
    print(result_final["judge_feedback"])