"""
File        : agents/mvp_advisor_agent.py
Triggered By: full_analysis, partial_idea
Tools       : groq_tool.py
Input       : workflow_state["market_data"] + workflow_state["rag_context"]
Output      : workflow_state["mvp_suggestions"]

Output Format:
workflow_state["mvp_suggestions"] → str
    Structured plain text with sections:
        ## Core Features
        ## Target User Personas
        ## 3-Month Build Scope
        ## Launch Sequence
    All grounded in market_data. No fabricated claims.

Responsibilities:
- Generate MVP feature list grounded in market data
- Prioritize features by user impact
- Suggest 3-month build scope for small team
- Reference pitch deck insights if rag_context available
"""

from src.core.decorators import (
    handle_errors,
    log_execution,
    track_timing,
    retry_on_failure,
)

from src.prompts.prompts import MVP_ADVISOR_PROMPT
from src.tools.groq_tool import text_call


class MVPAdvisorAgent:
    """
    MVP Advisor Agent responsible for generating a practical MVP
    recommendation based on market research and available startup-specific
    context.

    This agent operates as part of the multi-agent workflow and consumes
    market_data as the primary source of evidence. It can also use
    rag_context when relevant startup-specific information is available.

    The agent focuses on:
        - Identifying and prioritizing core MVP features.
        - Defining target user personas.
        - Suggesting a realistic 3-month build scope.
        - Establishing a launch sequence.
        - Separating evidence-based findings from product recommendations
          and unsupported assumptions.

    Input State:
        workflow_state["market_data"]:
            Market research and evidence collected by upstream agents.

        workflow_state["rag_context"]:
            List of retrieved startup-specific chunks from the RAG
            pipeline. Each chunk may contain text, metadata, RRF score,
            and reranker score.

    Output State:
        workflow_state["mvp_suggestions"]:
            Structured plain-text MVP recommendation generated by the LLM.

        workflow_state["pipeline_status"]["MVPAdvisorAgent"]:
            Updated to "success" when the agent completes successfully.

    Notes:
        Market data is treated as the primary source for market, customer,
        competitor, trend, and product evidence. RAG context is used only
        when it provides relevant startup-specific information.
    """

    @handle_errors
    @log_execution
    @track_timing
    @retry_on_failure
    def run(self, workflow_state: dict) -> dict:
        """
        Generate MVP recommendations from market data and RAG context.

        Parameters
        ----------
        workflow_state : dict
            Shared state passed between agents in the multi-agent workflow.
            The state must contain "market_data" and "rag_context".

        Returns
        -------
        dict
            Updated workflow state containing the generated MVP
            recommendations under "mvp_suggestions" and the updated
            MVPAdvisorAgent execution status.

        Notes
        -----
        Market data is used as the primary evidence source.

        RAG context is converted from a list of retrieved chunk
        dictionaries into a clean text representation before being
        included in the LLM prompt.

        If no RAG context is available, an explicit fallback message
        is provided instead of injecting an empty Python list into
        the prompt.
        """

        # ----------------------------------------------------
        # 1. Read market research and RAG context
        # ----------------------------------------------------

        market_data = workflow_state["market_data"]

        rag_context = workflow_state["rag_context"]

        # ----------------------------------------------------
        # 2. Normalize RAG context for prompt injection
        # ----------------------------------------------------

        if rag_context:

            rag_context_text = "\n\n".join(
                f"Chunk {index}:\n"
                f"Text: {chunk['text']}\n"
                f"Metadata: {chunk['metadata']}\n"
                f"Relevance Score: {chunk['rerank_score']}"
                + (
                    f"\nRRF Score: {chunk['rrf_score']}"
                    if "rrf_score" in chunk
                    else ""
                )
                for index, chunk in enumerate(rag_context, start=1)
            )

        else:

            rag_context_text = (
                "No relevant pitch-deck context available."
            )

        # ----------------------------------------------------
        # 3. Build user prompt
        # ----------------------------------------------------

        user_prompt = f"""
Analyze the following startup context and generate the MVP recommendation according to your system instructions.

### MARKET DATA

{market_data}

### RAG CONTEXT

{rag_context_text}

Use `MARKET DATA` as the primary source for market, customer, competitor, trend, and product evidence.

Use `RAG CONTEXT` only when it provides relevant startup-specific information such as product vision, pitch-deck insights, target users, business model, or existing product assumptions.

Preserve and use the source URLs provided in the context when making externally supported claims. Do not invent or modify sources.

Base the MVP recommendation on the evidence provided above. Clearly distinguish sourced facts from your own product recommendations and identify unsupported assumptions as requiring validation.

        """

        # ----------------------------------------------------
        # 4. Prepare system prompt and messages
        # ----------------------------------------------------

        system_prompt = MVP_ADVISOR_PROMPT

        messages = [
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_prompt
            }
        ]

        # ----------------------------------------------------
        # 5. Generate MVP recommendation
        # ----------------------------------------------------

        mvp_response = text_call(
            prompt=messages
        )

        # ----------------------------------------------------
        # 6. Store MVP recommendations in workflow state
        # ----------------------------------------------------

        workflow_state["mvp_suggestions"] = mvp_response

        # ----------------------------------------------------
        # 7. Update pipeline status
        # ----------------------------------------------------

        workflow_state["pipeline_status"]["MVPAdvisorAgent"] = (
            "success"
        )

        # ----------------------------------------------------
        # 8. Return updated workflow state
        # ----------------------------------------------------

        return workflow_state


# ----------------------------------------------------
# LOCAL TEST
# ----------------------------------------------------

if __name__ == "__main__":

    print("=" * 50)

    # ----------------------------------------------------
    # 1. Import MOCK_STATE_FULL
    # ----------------------------------------------------

    from tests.mock_workflow_state import MOCK_STATE_FULL

    # ----------------------------------------------------
    # 2. Initialize MVP Advisor Agent
    # ----------------------------------------------------

    agent = MVPAdvisorAgent()

    # ----------------------------------------------------
    # 3. Run MVP recommendation pipeline
    # ----------------------------------------------------

    workflow_state = agent.run(
        MOCK_STATE_FULL.copy()
    )

    # ----------------------------------------------------
    # 4. Print generated MVP recommendations
    # ----------------------------------------------------

    print(
        workflow_state["mvp_suggestions"]
    )