"""
File        : agents/mvp_advisor_agent.py
Triggered By: full_analysis, partial_idea
Tools       : groq_tool.py
Input       : workflow_state["market_data"] + workflow_state["rag_context"]
Output      : workflow_state["mvp_suggestions"]

Output Format:
workflow_state["mvp_suggestions"] → str
    Structured plain text with sections:
        ## Core Features
        ## Target User Personas
        ## 3-Month Build Scope
        ## Launch Sequence
    All grounded in market_data. No fabricated claims.

Responsibilities:
- Generate MVP feature list grounded in market data
- Prioritize features by user impact
- Suggest 3-month build scope for small team
- Reference pitch deck insights if rag_context available
"""

from src.core.decorators import (
    handle_errors,
    log_execution,
    track_timing,
    retry_on_failure,
)

from src.prompts.prompts import MVP_ADVISOR_PROMPT
from src.tools.groq_tool import text_call


class MVPAdvisorAgent:
    """
    MVP Advisor Agent responsible for generating a practical MVP
    recommendation using normalized startup context, market evidence,
    and startup-specific RAG context.

    Input State:
        workflow_state["startup_idea"]:
            Normalized startup idea.

        workflow_state["startup_type"]:
            Startup industry/category.

        workflow_state["market_data"]:
            Market research and evidence collected upstream.

        workflow_state["rag_context"]:
            Retrieved startup-specific context from the RAG pipeline.

    Output State:
        workflow_state["mvp_suggestions"]:
            Structured plain-text MVP recommendation generated by the LLM.

        workflow_state["pipeline_status"]["MVPAdvisorAgent"]:
            Updated to "success" when the agent completes successfully.

    Notes:
        Startup context defines what is being built.
        Market data provides external market evidence.
        RAG context provides startup-specific evidence.
    """

    @handle_errors
    @log_execution
    @track_timing
    @retry_on_failure
    def run(self, workflow_state: dict) -> dict:
        """
        Generate MVP recommendations from startup context,
        market data, and RAG context.
        """

        # ----------------------------------------------------
        # 1. Read startup context and research
        # ----------------------------------------------------

        startup_idea = workflow_state["startup_idea"]

        startup_type = workflow_state["startup_type"]

        market_data = workflow_state["market_data"]

        rag_context = workflow_state["rag_context"]

        # ----------------------------------------------------
        # 2. Normalize RAG context for prompt injection
        # ----------------------------------------------------

        if rag_context:

            rag_context_text = "\n\n".join(
                f"Chunk {index}:\n"
                f"Text: {chunk['text']}\n"
                f"Metadata: {chunk['metadata']}\n"
                f"Relevance Score: {chunk['rerank_score']}"
                + (
                    f"\nRRF Score: {chunk['rrf_score']}"
                    if "rrf_score" in chunk
                    else ""
                )
                for index, chunk in enumerate(
                    rag_context,
                    start=1
                )
            )

        else:

            rag_context_text = (
                "No relevant pitch-deck context available."
            )

        # ----------------------------------------------------
        # 3. Build user prompt
        # ----------------------------------------------------

        user_prompt = f"""
Analyze the following startup context and generate the MVP recommendation
according to your system instructions.

### STARTUP IDEA

{startup_idea}

### STARTUP TYPE

{startup_type}

### MARKET DATA

{market_data}

### RAG CONTEXT

{rag_context_text}

Use STARTUP IDEA and STARTUP TYPE to understand the exact startup being
evaluated.

Use MARKET DATA as the primary source for market, customer, competitor,
trend, and product evidence.

Use RAG CONTEXT only when it provides relevant startup-specific information
such as product vision, target users, business model, or existing assumptions.

Preserve and use source URLs provided in the supplied context.
Do not invent or modify sources.

Clearly distinguish sourced facts from product recommendations.
Identify unsupported assumptions as requiring validation.
"""

        # ----------------------------------------------------
        # 4. Prepare messages
        # ----------------------------------------------------

        system_prompt = MVP_ADVISOR_PROMPT

        messages = [
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_prompt
            }
        ]

        # ----------------------------------------------------
        # 5. Generate MVP recommendation
        # ----------------------------------------------------

        mvp_response = text_call(
            messages=messages
        )

        # ----------------------------------------------------
        # 6. Store MVP recommendations
        # ----------------------------------------------------

        workflow_state["mvp_suggestions"] = mvp_response

        # ----------------------------------------------------
        # 7. Update pipeline status
        # ----------------------------------------------------

        workflow_state["pipeline_status"]["MVPAdvisorAgent"] = (
            "success"
        )

        # ----------------------------------------------------
        # 8. Return updated workflow state
        # ----------------------------------------------------

        return workflow_state


# ----------------------------------------------------
# LOCAL TEST
# ----------------------------------------------------

if __name__ == "__main__":

    print("=" * 50)

    # ----------------------------------------------------
    # 1. Import MOCK_STATE_FULL
    # ----------------------------------------------------

    from tests.mock_workflow_state import MOCK_STATE_FULL

    # ----------------------------------------------------
    # 2. Initialize MVP Advisor Agent
    # ----------------------------------------------------

    agent = MVPAdvisorAgent()

    # ----------------------------------------------------
    # 3. Run MVP recommendation pipeline
    # ----------------------------------------------------

    workflow_state = agent.run(
        MOCK_STATE_FULL.copy()
    )

    # ----------------------------------------------------
    # 4. Print generated MVP recommendations
    # ----------------------------------------------------

    print(
        workflow_state["mvp_suggestions"]
    )
    
    print("\nERRORS:")
    print(
        workflow_state["errors"]
    )