"""
File        : agents/nurturing_agent.py
Triggered By:
    - partial_idea
    - nurturing

Tools:
    - groq_tool.py

Input:
    workflow_state["user_input"]
        Original user-provided startup concept.

    workflow_state["startup_idea"]
        Normalized startup concept.

    workflow_state["startup_type"]
        Startup category.

    workflow_state["market_data"]
        Market research and external evidence available for refinement.

    workflow_state["recommendations"]
        Upstream recommendations that may identify weaknesses or
        improvement opportunities.

Output:
    workflow_state["nurtured_idea"] → str
        Structured plain-text startup refinement containing:

            ## Refined Concept
            ## Value Proposition
            ## Missing Components Added
            ## Suggested Business Model
            ## Differentiators

Responsibilities:
    - Preserve the user's original startup intent.
    - Fill missing gaps in the concept.
    - Strengthen the value proposition.
    - Improve business model clarity.
    - Incorporate relevant market evidence.
    - Use available recommendations to strengthen the concept.
    - Produce a complete and coherent refined startup idea.

Processing Flow:
    1. Read startup context and upstream analysis.
    2. Load the nurturing system prompt.
    3. Build the startup refinement user prompt.
    4. Prepare system and user messages.
    5. Generate the refined concept through Groq.
    6. Store the generated concept in workflow state.
    7. Update NurturingAgent pipeline status.
    8. Return the updated workflow state.

Failure Handling:
    Agent execution, retry, timing, logging, and error handling are
    managed centrally by the shared decorators.
"""

from src.core.decorators import (
    handle_errors,
    log_execution,
    track_timing,
    retry_on_failure
)

from src.prompts.prompts import NURTURING_PROMPT
from src.tools.groq_tool import groq_tool


class NurturingAgent:
    """
    Refine and complete a partial startup concept using upstream
    workflow context and available market evidence.

    NurturingAgent operates in the partial_idea and nurturing workflows.
    Its purpose is to strengthen an existing startup concept rather than
    replace it with an unrelated idea.

    Input State
    -----------
    workflow_state["user_input"]:
        Original startup concept supplied by the user.

    workflow_state["startup_idea"]:
        Normalized startup concept used as the primary refinement target.

    workflow_state["startup_type"]:
        Startup category used to maintain domain relevance.

    workflow_state["market_data"]:
        External market research used to strengthen the refined concept.

    workflow_state["recommendations"]:
        Upstream improvement recommendations that may identify weaknesses
        or opportunities to incorporate into the refined concept.

    Output State
    ------------
    workflow_state["nurtured_idea"]:
        Structured plain-text startup concept generated by the LLM.

    workflow_state["pipeline_status"]["NurturingAgent"]:
        Set to "success" after successful execution.

    Core Responsibility
    -------------------
    The agent combines the user's original intent with available
    workflow evidence and transforms it into a clearer, more complete,
    and more actionable startup concept.

    The agent does not perform independent market research. It uses the
    market evidence already supplied by the workflow.
    """

    # ============================================================
    # DECORATOR STACK
    # Centralized execution logging, timing, retry, and error handling.
    # ============================================================

    @handle_errors
    @log_execution
    @track_timing
    @retry_on_failure
    def run(self, workflow_state: dict) -> dict:
        """
        Refine the supplied startup concept and store the result.

        Parameters
        ----------
        workflow_state : dict
            Shared workflow state containing the user's startup idea,
            normalized startup context, market evidence, and upstream
            recommendations.

        Returns
        -------
        dict
            Updated workflow state containing the generated
            "nurtured_idea" and successful pipeline status.

        Processing Stages
        -----------------
        1. Read required startup context and upstream information.
        2. Load the nurturing system prompt.
        3. Construct the startup refinement prompt.
        4. Prepare the Groq message payload.
        5. Generate the refined startup concept.
        6. Store the generated concept in workflow state.
        7. Mark NurturingAgent execution as successful.
        8. Return the updated workflow state.

        Notes
        -----
        The user's original intent remains the foundation of the
        refinement. Market data and recommendations are used to
        strengthen the concept without changing its fundamental intent.
        """

        # ============================================================
        # 1. Read startup context and upstream workflow data
        # ============================================================

        user_input = workflow_state["user_input"]

        startup_idea = workflow_state["startup_idea"]

        startup_type = workflow_state["startup_type"]

        market_data = workflow_state["market_data"]

        recommendations = workflow_state["recommendations"]

        # ============================================================
        # 2. Load the nurturing system prompt
        # ============================================================

        system_prompt = NURTURING_PROMPT

        # ============================================================
        # 3. Build the startup refinement user prompt
        # ============================================================

        user_prompt = f"""
Refine the startup opportunity using the information below.

=== USER INPUT ===
{user_input}

=== STARTUP DATA ===
Startup Idea: {startup_idea}
Startup Type: {startup_type}

=== RECOMMENDATIONS ===
{recommendations}

=== MARKET DATA ===
{market_data}

Analyze the user's original intent and the available evidence. Produce the structured startup refinement using the required output format.
"""

        # ============================================================
        # 4. Prepare structured LLM messages
        # ============================================================

        messages = [
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_prompt
            }
        ]

        # ============================================================
        # 5. Generate the refined startup concept
        # ============================================================

        groq_response = groq_tool.generate_text(
            messages=messages
        )

        # ============================================================
        # 6. Store the generated concept in workflow state
        # ============================================================

        workflow_state["nurtured_idea"] = (
            groq_response
        )

        # ============================================================
        # 7. Update NurturingAgent pipeline status
        # ============================================================

        workflow_state["pipeline_status"]["NurturingAgent"] = (
            "success"
        )

        # ============================================================
        # 8. Return the updated workflow state
        # ============================================================

        return workflow_state


# ================================================================
# STANDALONE TEST
# Allows NurturingAgent to be tested independently using the
# shared mock workflow state.
# ================================================================

if __name__ == "__main__":

    # ============================================================
    # 1. Load mock workflow state
    # ============================================================

    from tests.mock_workflow_state import MOCK_STATE_FULL

    workflow_state = MOCK_STATE_FULL.copy()

    # ============================================================
    # 2. Initialize NurturingAgent
    # ============================================================

    agent = NurturingAgent()

    # ============================================================
    # 3. Execute nurturing workflow
    # ============================================================

    result = agent.run(
        workflow_state
    )

    # ============================================================
    # 4. Display generated nurturing result
    # ============================================================

    print("RETURN TYPE:", type(result))
    print("RETURN VALUE:", result["nurtured_idea"])
    print("ERRORS:", workflow_state["errors"])