"""
File        : agents/nurturing_agent.py
Triggered By: partial_idea, nurturing
Tools       : groq_tool.py

Input:
    workflow_state["user_input"]
        Original partial startup idea or user-provided concept.

    workflow_state["market_data"]
        Market research and external evidence available for
        strengthening and validating the startup concept.

Output:
    workflow_state["nurtured_idea"] → str
        Structured plain text with sections:
            ## Refined Concept
            ## Value Proposition
            ## Missing Components Added
            ## Suggested Business Model
            ## Differentiators

        The refined concept should be grounded in the available
        market_data when relevant.

Responsibilities:
- Refine and complete a partial startup concept
- Identify and fill missing components
- Strengthen the value proposition
- Improve business model clarity
- Use available market evidence to strengthen the concept
- Preserve the user's original intent
- Return a complete and structured startup idea
"""

from src.core.decorators import (
    handle_errors,
    log_execution,
    track_timing,
    retry_on_failure
)

from src.prompts.prompts import NURTURING_PROMPT
from src.tools.groq_tool import text_call


class NurturingAgent:
    """
    Nurturing Agent responsible for transforming a partial startup
    concept into a more complete, structured, and actionable
    startup opportunity.

    This agent operates in the partial_idea and nurturing workflows.

    The agent combines:
        - The user's original startup concept
        - Available market research
        - The system-level nurturing instructions

    The agent focuses on:
        - Refining the original concept
        - Identifying missing components
        - Strengthening the value proposition
        - Improving business model clarity
        - Adding meaningful differentiators
        - Producing a more complete startup concept

    Input State:
        workflow_state["user_input"]:
            Original startup idea or user-provided concept that should
            be preserved and refined.

        workflow_state["market_data"]:
            Market research and external evidence that can be used
            to strengthen the refined concept.

    Output State:
        workflow_state["nurtured_idea"]:
            Structured plain-text startup concept generated by the LLM.

        workflow_state["pipeline_status"]["NurturingAgent"]:
            Updated to "success" when the agent completes successfully.

    Evidence Usage:
        Market data provides external context that can help identify
        market needs, opportunities, and relevant business considerations.

        The user's original input remains the starting point for the
        refinement process.

    Notes:
        The agent is intended to improve and complete the user's existing
        concept rather than replace it with an unrelated startup idea.
    """

    @handle_errors
    @log_execution
    @track_timing
    @retry_on_failure
    def run(self, workflow_state: dict) -> dict:
        """
        Refine a partial startup concept using market evidence.

        Parameters
        ----------
        workflow_state : dict
            Shared state passed between agents in the multi-agent workflow.

            Required fields:
                "user_input":
                    Original startup concept or user request.

                "market_data":
                    Available market research and external evidence.

        Returns
        -------
        dict
            Updated workflow state containing the refined startup
            concept under "nurtured_idea" and the updated
            NurturingAgent execution status.

        Notes
        -----
        The user's original intent and available market evidence are
        provided to the LLM together with the nurturing system prompt.

        The LLM generates the structured refined concept according to
        the required output format.

        The generated response is stored directly in
        workflow_state["nurtured_idea"].
        """

        # ----------------------------------------------------
        # 1. Read user input and market data
        # ----------------------------------------------------

        user_input = workflow_state["user_input"]

        market_data = workflow_state["market_data"]

        # ----------------------------------------------------
        # 2. Prepare system prompt
        # ----------------------------------------------------

        system_prompt = NURTURING_PROMPT

        # ----------------------------------------------------
        # 3. Build startup refinement prompt
        # ----------------------------------------------------

        user_prompt = f"""
Refine the startup opportunity using the following information.

=== USER INPUT ===
{user_input}
=== END USER INPUT ===

=== MARKET DATA ===
{market_data}
=== END MARKET DATA ===

Analyze the user's original intent and the available market evidence.
Then produce the structured startup refinement using the required format.
"""

        # ----------------------------------------------------
        # 4. Prepare LLM messages
        # ----------------------------------------------------

        messages = [
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_prompt
            }
        ]

        # ----------------------------------------------------
        # 5. Generate nurtured startup concept
        # ----------------------------------------------------

        groq_response = text_call(
            prompt=messages
        )

        # ----------------------------------------------------
        # 6. Store refined concept in workflow state
        # ----------------------------------------------------

        workflow_state["nurtured_idea"] = (
            groq_response
        )

        # ----------------------------------------------------
        # 7. Update pipeline status
        # ----------------------------------------------------

        workflow_state["pipeline_status"]["NurturingAgent"] = (
            "success"
        )

        # ----------------------------------------------------
        # 8. Return updated workflow state
        # ----------------------------------------------------

        return workflow_state


# ----------------------------------------------------
# LOCAL TEST
# ----------------------------------------------------

if __name__ == "__main__":

    # ----------------------------------------------------
    # 1. Load mock workflow state
    # ----------------------------------------------------

    from tests.mock_workflow_state import MOCK_STATE_FULL

    workflow_state = MOCK_STATE_FULL.copy()

    # ----------------------------------------------------
    # 2. Initialize Nurturing Agent
    # ----------------------------------------------------

    agent = NurturingAgent()

    # ----------------------------------------------------
    # 3. Run nurturing pipeline
    # ----------------------------------------------------

    workflow_state = agent.run(
        workflow_state
    )

    # ----------------------------------------------------
    # 4. Print refined startup concept
    # ----------------------------------------------------

    print(
        workflow_state["nurtured_idea"]
    )