"""
File        : agents/pdf_generator_agent.py
Triggered By:
    - pdf_request
    - ON-DEMAND ONLY

Tools:
    - pdf_tool.py

Input:
    workflow_state["final_report"]
        Final markdown report generated by ReportWriterAgent.

Output:
    workflow_state["pdf_path"] → str
        Path to the generated PDF file.

        Empty string or unchanged state when PDF generation is skipped
        because no final report is available.

PDF Rules:
    - Text response is always delivered through the normal workflow.
    - PDF generation occurs only when explicitly requested.
    - PDF generation is intended for full_analysis and partial_idea
      outputs.
    - general_chat and idea_exploration do not qualify for PDF output.
    - Automatic cleanup of unrequested PDFs is a later frontend concern.

Responsibilities:
    - Convert the final markdown report into a PDF.
    - Delegate PDF creation to pdf_tool.py.
    - Store the generated file path in workflow state.
    - Update PDFGeneratorAgent pipeline status.
    - Operate only when explicitly triggered by the PDF request flow.

Execution Flow:
    1. Read final_report from workflow state.
    2. Check whether a final report is available.
    3. Skip PDF generation when final_report is empty.
    4. Generate the PDF through write_pdf().
    5. Store the generated file path.
    6. Update pipeline status.
    7. Return the updated workflow state.

Failure Handling:
    Execution logging, timing, retry behavior, and exception handling
    are managed centrally by src/core/decorators.py.
"""

from src.core.decorators import (
    log_execution,
    track_timing,
    retry_on_failure,
    handle_errors
)

from src.tools.pdf_tool import write_pdf


class PDFGeneratorAgent:
    """
    Generate a PDF representation of the completed startup analysis
    report when explicitly requested.

    PDFGeneratorAgent is an on-demand output agent. It does not
    generate analysis, modify the final report, or perform any
    startup reasoning.

    Input State
    -----------
    workflow_state["final_report"]:
        Final markdown report produced by ReportWriterAgent.

    Output State
    ------------
    workflow_state["pdf_path"]:
        Path returned by write_pdf() after successful PDF generation.

    workflow_state["pipeline_status"]["PDFGeneratorAgent"]:
        Set to:
            - "skipped" when no final report is available.
            - "success" after successful PDF generation.

    Responsibilities
    ----------------
    - Validate that a final report exists.
    - Delegate PDF creation to pdf_tool.py.
    - Store the resulting file path.
    - Report execution status.

    Design Principle
    ----------------
    PDF generation is completely separate from report generation.

    The agent must not generate a PDF automatically as part of the
    normal analysis workflow. It is triggered only by an explicit
    PDF request.
    """

    # ============================================================
    # DECORATOR STACK
    # Provides centralized execution logging, timing measurement,
    # retry behavior, and exception handling.
    # ============================================================

    @handle_errors
    @log_execution
    @track_timing
    @retry_on_failure
    def run(self, workflow_state: dict) -> dict:
        """
        Generate a PDF from the final startup analysis report.

        Parameters
        ----------
        workflow_state : dict
            Shared workflow state containing the final report and
            pipeline status.

        Returns
        -------
        dict
            Updated workflow state containing the generated PDF path
            and PDFGeneratorAgent execution status.

        Processing Stages
        -----------------
        1. Read final_report from workflow state.
        2. Check whether final_report is available.
        3. Skip generation when the report is empty.
        4. Generate the PDF through write_pdf().
        5. Store the generated file path.
        6. Update pipeline status.
        7. Return the updated workflow state.

        Notes
        -----
        The agent does not generate or modify report content.

        PDF creation is delegated entirely to write_pdf().

        A missing final report results in a skipped PDF generation
        rather than attempting to create an empty document.
        """

        # ============================================================
        # 1. Read final report from workflow state
        # ============================================================

        final_report = workflow_state["final_report"]

        # ============================================================
        # 2. Check whether PDF generation can proceed
        # ============================================================

        if not final_report:

            workflow_state["pipeline_status"]["PDFGeneratorAgent"] = (
                "skipped"
            )

            return workflow_state

        # ============================================================
        # 3. Generate PDF through the PDF tool
        # ============================================================

        file_path = write_pdf(
            content=final_report
        )

        # ============================================================
        # 4. Store generated PDF path
        # ============================================================

        workflow_state["pdf_path"] = (
            file_path
        )

        # ============================================================
        # 5. Update PDFGeneratorAgent pipeline status
        # ============================================================

        workflow_state["pipeline_status"]["PDFGeneratorAgent"] = (
            "success"
        )

        # ============================================================
        # 6. Return updated workflow state
        # ============================================================

        return workflow_state


# ================================================================
# STANDALONE TEST
# Allows PDFGeneratorAgent to be tested independently using the
# shared mock workflow state and a sample final report.
# ================================================================

if __name__ == "__main__":

    # ============================================================
    # 1. Load mock workflow state
    # ============================================================

    from tests.mock_workflow_state import MOCK_STATE_FULL

    workflow_state = MOCK_STATE_FULL.copy()

    # ============================================================
    # 2. Provide sample final report for PDF generation
    # ============================================================

    workflow_state["final_report"] = """
# Startup Analysis Report

## 1. Market Overview

Personalized and subscription-based food delivery models are gaining attention in the food-delivery industry. In addition, student-focused meal delivery services are exploring subscription models, healthier meal options, and personalized food experiences.

**Sources:**

* [https://foodtech.folio3.com/blog/top-20-food-delivery-trends](https://foodtech.folio3.com/blog/top-20-food-delivery-trends)

* [https://example.com/student-food-delivery-trends](https://example.com/student-food-delivery-trends)

---

## 2. MVP Recommendations

### Core MVP Features

* **Student Registration & Preference System:** Student registration and preference collection.

* **Meal Selection & Recommendations:** Weekly meal-plan selection and personalized meal recommendations.

* **Subscription Management:** Tiffin subscription management.

* **Order Tracking:** Order and delivery tracking.

* **Feedback Mechanism:** Meal feedback collection.

* **Partnerships:** Local food-provider partnerships.

---

## 3. Tech Stack

* **Frontend:** React

* **Backend:** FastAPI

* **Database:** PostgreSQL

* **AI:** Python-based recommendation service

* **Deployment:** Docker

---

## 4. Risk Analysis

1. **Customer Acquisition Risk:** Students may be unwilling to switch from existing food-delivery services.

2. **Operational Risk:** Maintaining consistent food quality and delivery times may be difficult.

3. **Unit Economics Risk:** Low student budgets may make delivery costs difficult to absorb.

4. **Retention Risk:** Students may cancel subscriptions if meal variety is insufficient.

---

## 5. Startup Score

* **Overall Score:** 78

* **Highest Risk Flag:** Feasibility

* **Reasoning:** The concept addresses a practical problem with a clearly defined target audience, but operational feasibility and willingness to pay require further validation.

### Score Breakdown

| Dimension | Score |
| :--- | :--- |
| **Product** | 82 |
| **Market** | 80 |
| **Business Model** | 76 |
| **Scalability** | 74 |
| **Feasibility** | 70 |

---

## 6. Improvement Recommendations

1. **Validate student willingness to pay through a small campus pilot.**

   * **Reason:** Pricing and demand are critical assumptions.

   * **Source:** [https://example.com/student-food-delivery-trends](https://example.com/student-food-delivery-trends)

2. **Start with a limited weekly subscription plan before expanding into on-demand delivery.**

   * **Reason:** A limited subscription model can simplify initial operations.

   * **Source:** [https://example.com/subscription-food-models](https://example.com/subscription-food-models)

---

## 7. Pitch Deck Insights

*Note: Direct pitch deck text was not provided in the available workflow data. The following insights are structured from the supplied workflow data.*

### Concept

A personalized, AI-powered tiffin subscription service designed specifically for college students.

### Target Customer

College students.

### Value Proposition

Students receive convenient and affordable meals tailored to their food preferences and dietary requirements.

### Business Model

Weekly and monthly meal subscriptions with optional individual meal purchases.

### Differentiators

* Student-focused pricing

* Personalized meal recommendations

* Subscription convenience

---

## 8. Strategic Summary

The proposed business concept addresses student meal needs through an AI-powered, personalized tiffin delivery subscription service. Current market trends indicate growing interest in subscription models, personalization, and student-centric meal solutions. While the core product and market alignment show solid potential, primary challenges center around operational feasibility, customer acquisition, unit economics, and subscription retention. Operational validation—specifically testing student willingness to pay via campus pilots and streamlining early service using limited weekly plans—serves as the primary path forward before expanding capabilities.
"""

    # ============================================================
    # 3. Initialize PDFGeneratorAgent
    # ============================================================

    agent = PDFGeneratorAgent()

    # ============================================================
    # 4. Execute PDF generation
    # ============================================================

    workflow_state = agent.run(
        workflow_state.copy()
    )

    # ============================================================
    # 5. Display generated PDF path and errors
    # ============================================================

    print(
        workflow_state["pdf_path"]
    )
    
    print(
        workflow_state["errors"]
    )