"""
File        : agents/report_writer_agent.py
Triggered By: full_analysis, partial_idea
Tools       : gemini_tool.py

Input:
    Report-relevant outputs from the shared workflow_state.

    The agent collects the information required to build the final
    startup analysis report, including:

        - user_input
        - pitch_deck_text
        - market_data
        - web_search_results
        - rag_context
        - mvp_suggestions
        - tech_recommendations
        - risk_analysis
        - startup_score
        - recommendations
        - nurtured_idea

Output:
    workflow_state["final_report"] → str

    A complete Markdown startup analysis report containing:

        # Startup Analysis Report

        ## 1. Market Overview
        ## 2. MVP Recommendations
        ## 3. Tech Stack
        ## 4. Risk Analysis
        ## 5. Startup Score
        ## 6. Improvement Recommendations
        ## 7. Pitch Deck Insights
        ## 8. Strategic Summary

Responsibilities:
- Collect report-relevant outputs from previous agents.
- Normalize dictionaries and lists before prompt construction.
- Preserve meaningful technical details from previous agents.
- Preserve citations and URLs exactly as provided.
- Keep each workflow source clearly separated in the prompt.
- Prevent pipeline metadata from being treated as startup information.
- Provide Gemini with the complete workflow evidence.
- Assemble the final startup analysis report through Gemini.

Important:
    This agent is a report assembly agent.

    It does not perform new market research, independently evaluate
    the startup, or create unsupported facts.

    The previous agent outputs supplied through workflow_state are
    treated as the source of truth for the final report.
"""

from src.core.decorators import (
    log_execution,
    track_timing,
    retry_on_failure,
    handle_errors
)

from src.prompts.prompts import REPORT_WRITER_PROMPT
from src.tools.gemini_tool import text_call

import json


def to_prompt_string(value) -> str:
    """
    Convert workflow_state data into a clean string representation
    suitable for inclusion in the Gemini prompt.

    Parameters
    ----------
    value :
        Any value from workflow_state that needs to be passed to
        the report-writing prompt.

    Returns
    -------
    str
        A readable string representation of the supplied value.

        Dictionaries and lists are converted into formatted JSON
        so that nested workflow structures remain readable.

        Strings and other values are converted using str().

    Notes
    -----
    This helper only prepares workflow data for prompt construction.
    It does not modify the original workflow_state values.
    """

    if isinstance(value, (dict, list)):
        return json.dumps(
            value,
            indent=2,
            ensure_ascii=False,
            default=str
        )

    return str(value)


class ReportWriterAgent:
    """
    Report Writer Agent responsible for assembling the final startup
    analysis report from the outputs produced by previous agents.

    This agent operates near the end of the multi-agent workflow after
    the required startup analysis components have been generated.

    The agent does not perform independent research or create new
    startup analysis. Instead, it organizes the information already
    present in workflow_state and provides that information to Gemini
    using a clearly structured prompt.

    The agent combines:
        - Original user input
        - Pitch-deck information
        - Market research
        - Web search evidence
        - RAG context
        - MVP recommendations
        - Technology recommendations
        - Risk analysis
        - Startup score
        - Improvement recommendations
        - Nurtured startup idea

    Input State:
        workflow_state:
            Shared state containing outputs generated by previous
            agents in the multi-agent pipeline.

    Output State:
        workflow_state["final_report"]:
            Final Markdown startup analysis report generated by Gemini.

        workflow_state["pipeline_status"]["ReportWriterAgent"]:
            Updated to "success" when the report is generated successfully.

    Core Responsibility:
        Convert multiple heterogeneous workflow outputs into one
        coherent final report without introducing unsupported
        information.

    Important:
        The report writer should preserve the evidence supplied by
        previous agents, including meaningful technical details,
        citations, and URLs.

        Pipeline metadata such as execution logs, retry counters,
        and internal status information is not treated as startup
        analysis data.
    """

    @log_execution
    @track_timing
    @retry_on_failure
    @handle_errors
    def run(self, workflow_state: dict) -> dict:
        """
        Assemble the final startup analysis report from workflow_state.

        Parameters
        ----------
        workflow_state : dict
            Shared workflow state containing outputs from the previous
            agents participating in the startup analysis pipeline.

        Returns
        -------
        dict
            Updated workflow_state containing the generated final
            report under "final_report" and the updated
            ReportWriterAgent pipeline status.

        Processing Flow
        ---------------
        STEP 1:
            Collect only the workflow fields relevant to the final
            startup report.

        STEP 2:
            Normalize lists and dictionaries into readable strings
            using to_prompt_string().

        STEP 3:
            Build a clearly separated user prompt containing all
            report-relevant workflow information.

        STEP 4:
            Combine REPORT_WRITER_PROMPT with the workflow data.

        STEP 5:
            Send the complete report-writing prompt to Gemini.

        STEP 6:
            Store the generated Markdown report in
            workflow_state["final_report"].

        STEP 7:
            Mark ReportWriterAgent as successfully completed.

        STEP 8:
            Return the updated workflow_state.

        Notes
        -----
        Gemini receives the workflow data as the source of truth.

        The report-writing prompt explicitly prevents the model from
        performing additional research or inventing facts that are
        not present in the supplied workflow data.
        """

        # ==============================================================
        # STEP 1 — COLLECT REPORT-RELEVANT WORKFLOW DATA
        # ==============================================================

        report_data = {
            "user_input": workflow_state.get(
                "user_input",
                ""
            ),

            "pitch_deck_text": workflow_state.get(
                "pitch_deck_text",
                []
            ),

            "market_data": workflow_state.get(
                "market_data",
                ""
            ),

            "web_search_results": workflow_state.get(
                "web_search_results",
                ""
            ),

            "rag_context": workflow_state.get(
                "rag_context",
                []
            ),

            "mvp_suggestions": workflow_state.get(
                "mvp_suggestions",
                ""
            ),

            "tech_recommendations": workflow_state.get(
                "tech_recommendations",
                ""
            ),

            "risk_analysis": workflow_state.get(
                "risk_analysis",
                ""
            ),

            "startup_score": workflow_state.get(
                "startup_score",
                {}
            ),

            "recommendations": workflow_state.get(
                "recommendations",
                []
            ),

            "nurtured_idea": workflow_state.get(
                "nurtured_idea",
                ""
            ),

        }

        # ==============================================================
        # STEP 2 — NORMALIZE ALL WORKFLOW DATA
        # ==============================================================

        report_data = {
            key: to_prompt_string(value)
            for key, value in report_data.items()
        }

        # ==============================================================
        # STEP 3 — BUILD STRUCTURED USER PROMPT
        # ==============================================================

        user_prompt = f"""
Generate the final BizRadar startup analysis report using ONLY the workflow
data provided below.

The supplied workflow data is the complete source of truth.

Do not use external knowledge.
Do not perform additional research.
Do not invent facts, statistics, competitors, technologies, recommendations,
market claims, scores, risks, or conclusions.

You may reorganize, combine overlapping information, improve readability,
and create useful Markdown formatting and subsections.

==============================
USER INPUT
==============================
{report_data["user_input"]}

==============================
PITCH DECK TEXT
==============================
{report_data["pitch_deck_text"]}

==============================
MARKET DATA
==============================
{report_data["market_data"]}

==============================
WEB SEARCH RESULTS
==============================
{report_data["web_search_results"]}

==============================
RAG CONTEXT
==============================
{report_data["rag_context"] if report_data["rag_context"] != "[]" else "Not Provided"}

==============================
MVP SUGGESTIONS
==============================
{report_data["mvp_suggestions"]}

==============================
TECH RECOMMENDATIONS
==============================
{report_data["tech_recommendations"]}

==============================
RISK ANALYSIS
==============================
{report_data["risk_analysis"]}

==============================
STARTUP SCORE
==============================
{report_data["startup_score"]}

==============================
IMPROVEMENT RECOMMENDATIONS
==============================
{report_data["recommendations"]}

==============================
NURTURED IDEA
==============================
{report_data["nurtured_idea"]}

==============================
END WORKFLOW DATA
==============================

Assemble the supplied information into the required eight-section Markdown
startup analysis report.

Preserve all meaningful information and citations.

Do not add facts, assumptions, recommendations, or external knowledge.
"""

        # ==============================================================
        # STEP 4 — COMBINE SYSTEM PROMPT + USER DATA
        # ==============================================================

        final_prompt = (
            REPORT_WRITER_PROMPT
            + "\n\n"
            + user_prompt
        )

        # ==============================================================
        # STEP 5 — CALL GEMINI
        # ==============================================================

        gemini_response = text_call(
            user_prompt=final_prompt
        )

        # ==============================================================
        # STEP 6 — STORE FINAL REPORT
        # ==============================================================

        workflow_state["final_report"] = (
            gemini_response
        )

        # ==============================================================
        # STEP 7 — UPDATE PIPELINE STATUS
        # ==============================================================

        workflow_state["pipeline_status"]["ReportWriterAgent"] = (
            "success"
        )

        # ==============================================================
        # STEP 8 — RETURN WORKFLOW STATE
        # ==============================================================

        return workflow_state


# ==============================================================
# LOCAL TEST
# ==============================================================

if __name__ == "__main__":

    # --------------------------------------------------------------
    # TEST WORKFLOW STATE
    # --------------------------------------------------------------

    workflow_state = {

        # ── INPUTS ──────────────────────────────────────────
        "user_input": "AI-powered tiffin delivery for college students",

        "pitch_deck_text": [
            "Problem: College students need affordable, convenient, and healthy meals.",
            "Solution: Personalized tiffin delivery based on student preferences.",
            "Target Market: College students living away from home."
        ],

        # ── LLM AS JUDGE ────────────────────────────────────
        "judge_feedback": {
            "mid_pipeline": (
                "The startup addresses a clear student food problem, "
                "but willingness to pay requires validation."
            ),
            "final": (
                "The concept has potential but needs stronger market validation "
                "and differentiation."
            )
        },

        # ── INTENT & PLAN ───────────────────────────────────
        "intent": "",
        "execution_plan": [],

        # ── AGENT OUTPUTS ───────────────────────────────────
        "market_data": """
Personalized and subscription-based food delivery models are gaining
attention in the food-delivery industry.

Source:
https://foodtech.folio3.com/blog/top-20-food-delivery-trends
""",

        "web_search_results": """
Student-focused meal delivery services are exploring subscription models,
healthier meal options, and personalized food experiences.

Source:
https://example.com/student-food-delivery-trends
""",

        "rag_context": [
            {
                "content": (
                    "College students prioritize affordability, convenience, "
                    "and predictable meal availability."
                ),
                "metadata": {
                    "source": "student_food_research.pdf",
                    "page": 4
                }
            },
            {
                "content": (
                    "Subscription models can provide predictable recurring "
                    "revenue for meal-delivery businesses."
                ),
                "metadata": {
                    "source": "startup_business_models.pdf",
                    "page": 12
                }
            }
        ],

        "mvp_suggestions": """
1. Student registration and preference collection.
2. Weekly meal-plan selection.
3. Personalized meal recommendations.
4. Tiffin subscription management.
5. Order and delivery tracking.
""",

        "tech_recommendations": """
Frontend: React
Backend: FastAPI
Database: PostgreSQL
AI: Python-based recommendation service
Deployment: Docker
""",

        "risk_analysis": """
1. Customer Acquisition Risk:
Students may be unwilling to switch from existing food-delivery services.

2. Operational Risk:
Maintaining consistent food quality and delivery times may be difficult.

3. Unit Economics Risk:
Low student budgets may make delivery costs difficult to absorb.

4. Retention Risk:
Students may cancel subscriptions if meal variety is insufficient.
""",

        "startup_score": {
            "score": 78,
            "reasoning": (
                "The concept addresses a practical problem with a clearly "
                "defined target audience, but operational feasibility and "
                "willingness to pay require further validation."
            ),
            "breakdown": {
                "market": 80,
                "product": 82,
                "business_model": 76,
                "scalability": 74,
                "feasibility": 70
            },
            "highest_risk_flag": "feasibility"
        },

        "recommendations": [
            {
                "rank": 1,
                "recommendation": (
                    "Validate student willingness to pay through a small "
                    "campus pilot."
                ),
                "reason": "Pricing and demand are critical assumptions.",
                "source_url": "https://example.com/student-food-delivery-trends"
            },
            {
                "rank": 2,
                "recommendation": (
                    "Start with a limited weekly subscription plan before "
                    "expanding into on-demand delivery."
                ),
                "reason": "A limited subscription model can simplify initial operations.",
                "source_url": "https://example.com/subscription-food-models"
            }
        ],

        "generated_ideas": [
            {
                "rank": 1,
                "idea": "Personalized weekly tiffin subscriptions for college students.",
                "market_signal": (
                    "Growing interest in personalized food experiences."
                ),
                "source_url": (
                    "https://foodtech.folio3.com/blog/top-20-food-delivery-trends"
                )
            },
            {
                "rank": 2,
                "idea": "Budget-focused healthy meal subscriptions for students.",
                "market_signal": (
                    "Students prioritize affordability and convenience."
                ),
                "source_url": "https://example.com/student-food-delivery-trends"
            }
        ],

        "nurtured_idea": """
## Refined Concept

A personalized tiffin subscription service designed specifically
for college students.

## Value Proposition

Students receive convenient and affordable meals tailored to their
food preferences and dietary requirements.

## Missing Components Added

- Student preference system
- Subscription management
- Meal feedback mechanism
- Local food-provider partnerships

## Suggested Business Model

Weekly and monthly meal subscriptions with optional individual
meal purchases.

## Differentiators

- Student-focused pricing
- Personalized meal recommendations
- Subscription convenience
""",

        "advancement_plan": """
## Current Stage Assessment

The concept has a clear target customer and problem but requires
stronger validation around willingness to pay and operational feasibility.

## Recommended Advancement

Launch a small campus-based personalized subscription pilot.

## Why This Advancement

A controlled pilot can validate demand, pricing, retention, and meal
preferences before significant expansion.

## Implementation Approach

Start with one college, a limited menu, and a small group of students.

## Next Steps

### Validate

Test willingness to pay and preferred subscription pricing.

### Build

Create a basic ordering and subscription workflow.

### Test/Measure

Measure retention, satisfaction, repeat orders, and delivery issues.
""",

        "chat_response": "",

        "final_report": "",
        "pdf_path": "",

        # ── PIPELINE TRACKING ────────────────────────────────
        "pipeline_status": {},
        "agent_retry_count": {},
        "execution_log": [],
        "errors": []
    }

    # --------------------------------------------------------------
    # INITIALIZE REPORT WRITER AGENT
    # --------------------------------------------------------------

    agent = ReportWriterAgent()

    # --------------------------------------------------------------
    # RUN REPORT GENERATION
    # --------------------------------------------------------------

    workflow_state = agent.run(
        workflow_state.copy()
    )

    # --------------------------------------------------------------
    # DISPLAY FINAL REPORT
    # --------------------------------------------------------------

    print(
        workflow_state["final_report"]
    )