"""
Report Writer Agent

Responsibility:
    Assemble the final BizRadar startup analysis report from existing
    workflow outputs.

This agent does NOT perform:
    - Market research
    - RAG retrieval
    - Risk analysis
    - MVP generation
    - New strategic reasoning
    - External research

It only transforms supplied workflow data into a structured Markdown report.

Startup Context:
    startup_idea and startup_type are used only for report framing and
    startup identity.

    They must NOT be used to generate new:
        - facts
        - analysis
        - recommendations
        - strategies
        - risks
        - features
        - business models
        - technical decisions
        - conclusions

The workflow outputs remain the authoritative source of report content.
"""

import json

from src.core.decorators import (
    handle_errors,
    log_execution,
    track_timing,
    retry_on_failure
)

from src.prompts.prompts import REPORT_WRITER_PROMPT
from src.tools.gemini_tool import gemini_tool


def to_prompt_string(value):
    """
    Convert workflow data into readable prompt text.

    Dictionaries and lists are converted into formatted JSON.
    Other values are converted using str().

    This helper only prepares data for the Gemini prompt.
    It does not modify workflow_state.
    """

    if isinstance(value, (dict, list)):
        return json.dumps(
            value,
            indent=2,
            ensure_ascii=False,
            default=str
        )

    return str(value)


class ReportWriterAgent:
    """
    Assemble the final startup analysis report.

    The agent receives outputs generated by previous workflow stages
    and converts them into one coherent Markdown report.

    Input State:
        workflow_state["user_input"]
            Original user request.

        workflow_state["startup_idea"]
            Normalized startup idea used only to identify and frame
            the startup being reported.

        workflow_state["startup_type"]
            Startup category used only as supporting report context.

        Other workflow fields:
            Existing outputs from market research, RAG, MVP,
            technology, risk, scoring, nurturing, and advancement agents.

    Output State:
        workflow_state["final_report"]
            Final Markdown startup analysis report.

        workflow_state["pipeline_status"]["ReportWriterAgent"]
            Execution status.

    Core Responsibility:
        Assemble existing workflow information without creating
        new substantive information.
    """

    @handle_errors
    @log_execution
    @track_timing
    @retry_on_failure
    def run(self, workflow_state: dict) -> dict:
        """
        Generate the final Markdown startup analysis report.

        Startup context is included only for report framing.

        startup_idea and startup_type must never become independent
        sources for generating new analysis or recommendations.
        """

        # ==============================================================
        # STEP 1 — COLLECT REPORT-RELEVANT WORKFLOW DATA
        # ==============================================================

        report_data = {
            "user_input": workflow_state.get(
                "user_input",
                ""
            ),

            # ----------------------------------------------------------
            # Startup identity/context
            # ----------------------------------------------------------
            #
            # These fields identify what startup the report describes.
            # They are NOT independent sources of analytical content.
            #
            "startup_idea": workflow_state.get(
                "startup_idea",
                ""
            ),

            "startup_type": workflow_state.get(
                "startup_type",
                ""
            ),

            "pitch_deck_text": workflow_state.get(
                "pitch_deck_text",
                []
            ),

            "market_data": workflow_state.get(
                "market_data",
                ""
            ),

            "web_search_results": workflow_state.get(
                "web_search_results",
                ""
            ),

            "rag_context": workflow_state.get(
                "rag_context",
                []
            ),

            "mvp_suggestions": workflow_state.get(
                "mvp_suggestions",
                ""
            ),

            "tech_recommendations": workflow_state.get(
                "tech_recommendations",
                ""
            ),

            "risk_analysis": workflow_state.get(
                "risk_analysis",
                ""
            ),

            "startup_score": workflow_state.get(
                "startup_score",
                {}
            ),

            "recommendations": workflow_state.get(
                "recommendations",
                []
            ),

            "nurtured_idea": workflow_state.get(
                "nurtured_idea",
                ""
            ),

            "advancement_plan": workflow_state.get(
                "advancement_plan",
                ""
            ),
        }

        # ==============================================================
        # STEP 2 — NORMALIZE WORKFLOW DATA
        # ==============================================================

        report_data = {
            key: to_prompt_string(value)
            for key, value in report_data.items()
        }

        # ==============================================================
        # STEP 3 — BUILD STRUCTURED REPORT-WRITING PROMPT
        # ==============================================================

        user_prompt = f"""
Generate the final BizRadar startup analysis report using only the supplied workflow data.

=== STARTUP CONTEXT ===

STARTUP IDEA:
{report_data["startup_idea"]}

STARTUP TYPE:
{report_data["startup_type"]}

USER INPUT:
{report_data["user_input"]}

=== PITCH DECK TEXT ===
{report_data["pitch_deck_text"]}

=== MARKET DATA ===
{report_data["market_data"]}

=== WEB SEARCH RESULTS ===
{report_data["web_search_results"]}

=== RAG CONTEXT ===
{
    report_data["rag_context"]
    if report_data["rag_context"] != "[]"
    else "Not Provided"
}

=== MVP SUGGESTIONS ===
{report_data["mvp_suggestions"]}

=== TECH RECOMMENDATIONS ===
{report_data["tech_recommendations"]}

=== RISK ANALYSIS ===
{report_data["risk_analysis"]}

=== STARTUP SCORE ===
{report_data["startup_score"]}

=== IMPROVEMENT RECOMMENDATIONS ===
{report_data["recommendations"]}

=== NURTURED IDEA ===
{report_data["nurtured_idea"]}

=== ADVANCEMENT PLAN ===
{report_data["advancement_plan"]}

=== END WORKFLOW DATA ===
"""

        # ==============================================================
        # STEP 4 — COMBINE SYSTEM PROMPT + WORKFLOW DATA
        # ==============================================================

        final_prompt = (
            REPORT_WRITER_PROMPT
            + "\n\n"
            + user_prompt
        )

        # ==============================================================
        # STEP 5 — GENERATE FINAL REPORT USING GEMINI
        # ==============================================================

        final_report = gemini_tool.generate_text(
            user_prompt=final_prompt
        )

        # ==============================================================
        # STEP 6 — STORE FINAL REPORT
        # ==============================================================

        workflow_state["final_report"] = (
            final_report
        )

        # ==============================================================
        # STEP 7 — UPDATE PIPELINE STATUS
        # ==============================================================

        workflow_state[
            "pipeline_status"
        ][
            "ReportWriterAgent"
        ] = "success"

        # ==============================================================
        # STEP 8 — RETURN UPDATED WORKFLOW STATE
        # ==============================================================

        return workflow_state


# ==============================================================
# LOCAL TEST
# ==============================================================

if __name__ == "__main__":

    from tests.mock_workflow_state import MOCK_STATE_FULL

    # Use the shared mock workflow state instead of maintaining
    # a separate hardcoded report-writer test dataset.
    workflow_state = MOCK_STATE_FULL.copy()

    # Ensure the new startup context exists in the mock state.
    workflow_state.setdefault(
        "startup_idea",
        ""
    )

    workflow_state.setdefault(
        "startup_type",
        ""
    )

    agent = ReportWriterAgent()

    workflow_state = agent.run(
        workflow_state
    )

    print(
        workflow_state["final_report"]
    )

    print(
        workflow_state["errors"]
    )