"""
File        : agents/risk_analyst_agent.py
Triggered By: full_analysis
Tools       : gemini_tool.py

Input:
    workflow_state["market_data"]
        External market, customer, competitor, trend, and ecosystem
        evidence produced by upstream research agents.

    workflow_state["mvp_suggestions"]
        Proposed MVP features, target users, build scope, and
        launch sequence generated by the MVP Advisor Agent.

    workflow_state["rag_context"]
        Relevant startup-specific context retrieved from the pitch
        deck or other indexed documents through the RAG pipeline.

Output:
    workflow_state["risk_analysis"] → str
        Structured plain text per MVP feature:
            ### Feature: <Feature Name>
            Risk:
            Why:
            Impact:
            Mitigation:

        Followed by:
            ## Highest Business Risk
            Risk:
            Reason:
            Mitigation:

Responsibilities:
- Evaluate market risks with mitigation
- Evaluate technical risks with mitigation
- Evaluate execution risks with mitigation
- Evaluate risks specific to proposed MVP features
- Use pitch-deck context to identify startup-specific risks
- Ground risks in available market, MVP, and RAG evidence
- Identify cross-cutting risks
- Identify the single highest business risk
- Avoid generic risks that cannot be tied to available evidence
- Clearly distinguish evidence-supported risks from assumptions
  requiring validation
"""

from src.core.decorators import (
    handle_errors,
    log_execution,
    track_timing,
    retry_on_failure,
)

from src.prompts.prompts import RISK_ANALYST_PROMPT
from src.tools.gemini_tool import text_call


class RiskAnalystAgent:
    """
    Risk Analyst Agent responsible for identifying and evaluating
    material startup risks using three complementary sources of evidence:
    market data, MVP recommendations, and RAG-retrieved pitch-deck context.

    This agent operates in the full_analysis workflow after the MVP
    recommendation has been generated.

    The agent evaluates:
        - Market risks
        - Technical risks
        - Execution risks
        - MVP feature-level risks
        - Startup-specific risks revealed by the pitch deck
        - Cross-cutting business risks
        - The single highest business risk

    Input State:
        workflow_state["market_data"]:
            External market and ecosystem evidence produced by
            upstream research agents.

        workflow_state["mvp_suggestions"]:
            Concrete MVP features, target users, build scope,
            and launch sequence being evaluated for risk.

        workflow_state["rag_context"]:
            Relevant startup-specific evidence retrieved from the
            pitch deck or other indexed documents. This may provide
            additional context about the product vision, target users,
            business model, technical dependencies, operational
            assumptions, or other startup-specific factors.

    Output State:
        workflow_state["risk_analysis"]:
            Structured risk analysis generated by the LLM.

        workflow_state["pipeline_status"]["RiskAnalystAgent"]:
            Updated to "success" when the agent completes successfully.

    Evidence Roles:
        Market data:
            Provides external market, customer, competitor, trend,
            and ecosystem evidence.

        MVP suggestions:
            Define the concrete product scope whose risks are being
            evaluated.

        RAG context:
            Provides startup-specific evidence from the pitch deck
            that may reveal risks not visible in external market data
            or the MVP description alone.

    Notes:
        All three sources should be considered together when relevant.
        RAG context is supporting startup-specific evidence and should
        not be treated as automatically verified fact. Unsupported
        assumptions must be identified as requiring validation.
    """

    @handle_errors
    @log_execution
    @track_timing
    @retry_on_failure
    def run(self, workflow_state: dict) -> dict:
        """
        Analyze material startup risks using market data, MVP suggestions,
        and startup-specific RAG context.

        Parameters
        ----------
        workflow_state : dict
            Shared state passed between agents in the multi-agent workflow.

            Required fields:
                "market_data":
                    External market and ecosystem evidence.

                "mvp_suggestions":
                    Proposed MVP scope and feature recommendations.

                "rag_context":
                    Relevant startup-specific chunks retrieved from the
                    pitch deck or other indexed documents.

        Returns
        -------
        dict
            Updated workflow state containing the generated risk analysis
            under "risk_analysis" and the updated RiskAnalystAgent execution
            status.

        Notes
        -----
        Market data provides external evidence for evaluating market and
        ecosystem-related risks.

        MVP suggestions define the concrete product and feature scope whose
        technical, execution, and business risks are being evaluated.

        RAG context provides startup-specific evidence that can expose risks
        arising from pitch-deck assumptions, product requirements, target
        users, business model, technical dependencies, or operational plans.

        RAG context is converted from retrieved chunk dictionaries into a
        clean text representation before being included in the prompt.

        If no relevant RAG context is available, an explicit fallback message
        is used instead of injecting an empty Python list.

        The final analysis should prioritize material risks supported by the
        available evidence and avoid generic risk lists.
        """

        # ----------------------------------------------------
        # 1. Read market data and MVP recommendations
        # ----------------------------------------------------

        market_data = workflow_state["market_data"]

        mvp_suggestions = workflow_state["mvp_suggestions"]

        # ----------------------------------------------------
        # 2. Read and normalize RAG context
        # ----------------------------------------------------

        rag_context = workflow_state.get(
            "rag_context",
            []
        )

        if rag_context:

            rag_context_text = "\n\n".join(
                f"Chunk {index}:\n"
                f"Text: {chunk['text']}\n"
                f"Metadata: {chunk['metadata']}\n"
                f"Relevance Score: {chunk['rerank_score']}"
                + (
                    f"\nRRF Score: {chunk['rrf_score']}"
                    if "rrf_score" in chunk
                    else ""
                )
                for index, chunk in enumerate(
                    rag_context,
                    start=1
                )
            )

        else:

            rag_context_text = (
                "No relevant pitch-deck context available."
            )

        # ----------------------------------------------------
        # 3. Prepare system prompt
        # ----------------------------------------------------

        system_prompt = RISK_ANALYST_PROMPT

        # ----------------------------------------------------
        # 4. Build user prompt
        # ----------------------------------------------------

        user_prompt = f"""
Analyze the startup using the following evidence according to the system instructions.

=== START MARKET DATA ===
{market_data}
=== END MARKET DATA ===

=== START MVP SUGGESTIONS ===
{mvp_suggestions}
=== END MVP SUGGESTIONS ===

=== START RAG CONTEXT / PITCH DECK ===
{rag_context_text}
=== END RAG CONTEXT / PITCH DECK ===

Use MARKET DATA for external market, customer, competitor, trend, and ecosystem evidence.

Use MVP SUGGESTIONS as the concrete product scope whose risks must be evaluated.

Use RAG CONTEXT when it provides relevant startup-specific evidence such as product assumptions, target users, business model, technical dependencies, operational constraints, or pitch-deck claims.

Clearly distinguish evidence-supported risks from assumptions that require validation.

Identify the material feature-level risks, cross-cutting risks, and the single highest business risk.
"""

        # ----------------------------------------------------
        # 5. Combine system and user instructions
        # ----------------------------------------------------

        message = (
            system_prompt
            + user_prompt
        )

        # ----------------------------------------------------
        # 6. Generate risk analysis
        # ----------------------------------------------------

        risk_analysis_response = text_call(
            user_prompt=message
        )

        # ----------------------------------------------------
        # 7. Store risk analysis in workflow state
        # ----------------------------------------------------

        workflow_state["risk_analysis"] = (
            risk_analysis_response
        )

        # ----------------------------------------------------
        # 8. Update pipeline status
        # ----------------------------------------------------

        workflow_state["pipeline_status"]["RiskAnalystAgent"] = (
            "success"
        )

        # ----------------------------------------------------
        # 9. Return updated workflow state
        # ----------------------------------------------------

        return workflow_state


# ----------------------------------------------------
# LOCAL TEST
# ----------------------------------------------------

if __name__ == "__main__":

    # ----------------------------------------------------
    # 1. Load mock workflow state
    # ----------------------------------------------------

    from tests.mock_workflow_state import MOCK_STATE_FULL

    workflow_state = MOCK_STATE_FULL.copy()

    # ----------------------------------------------------
    # 2. Initialize Risk Analyst Agent
    # ----------------------------------------------------

    agent = RiskAnalystAgent()

    # ----------------------------------------------------
    # 3. Run risk analysis pipeline
    # ----------------------------------------------------

    workflow_state = agent.run(
        workflow_state
    )

    # ----------------------------------------------------
    # 4. Print generated risk analysis
    # ----------------------------------------------------

    print(
        workflow_state["risk_analysis"]
    )