"""
File        : agents/risk_analyst_agent.py
Triggered By:
    - full_analysis

Tools:
    - gemini_tool.py

Input:
    workflow_state["startup_idea"]
        Normalized startup concept being evaluated.

    workflow_state["startup_type"]
        Startup industry/category.

    workflow_state["market_data"]
        External market, customer, competitor, trend, and ecosystem
        evidence produced by upstream research agents.

    workflow_state["mvp_suggestions"]
        Proposed MVP features, target users, build scope, and launch
        sequence generated by MVPAdvisorAgent.

    workflow_state["rag_context"]
        Startup-specific context retrieved from the pitch deck or
        indexed documents through RAGAgent.

Output:
    workflow_state["risk_analysis"] → str
        Structured plain-text risk analysis containing:

            ### Feature: <Feature Name>
            Risk:
            Why:
            Impact:
            Mitigation:

        Followed by:

            ## Highest Business Risk
            Risk:
            Reason:
            Mitigation:

Responsibilities:
    - Evaluate market risks.
    - Evaluate technical risks.
    - Evaluate execution risks.
    - Evaluate MVP feature-level risks.
    - Use RAG context to identify startup-specific risks.
    - Ground risks in available market, MVP, and RAG evidence.
    - Identify cross-cutting risks.
    - Identify the single highest business risk.
    - Distinguish evidence-supported risks from assumptions requiring
      validation.
    - Avoid generic risks that cannot be tied to available evidence.

Evidence Roles:
    STARTUP IDEA:
        Defines the startup being evaluated.

    STARTUP TYPE:
        Provides broader industry and category context.

    MARKET DATA:
        Provides external market, customer, competitor, trend, and
        ecosystem evidence.

    MVP SUGGESTIONS:
        Define the concrete product scope whose risks are evaluated.

    RAG CONTEXT:
        Provides startup-specific evidence from the pitch deck or
        indexed documents.

Execution Flow:
    1. Read startup context.
    2. Read market data and MVP recommendations.
    3. Read and normalize RAG context.
    4. Prepare the risk-analysis system prompt.
    5. Build the evidence-based user prompt.
    6. Combine system and user instructions.
    7. Generate the risk analysis.
    8. Store the generated risk analysis.
    9. Update pipeline status.
    10. Return the updated workflow state.

Failure Handling:
    Execution logging, timing, retry behavior, and exception handling
    are managed centrally by src/core/decorators.py.
"""

from src.core.decorators import (
    handle_errors,
    log_execution,
    track_timing,
    retry_on_failure,
)

from src.prompts.prompts import RISK_ANALYST_PROMPT
from src.tools.gemini_tool import text_call


class RiskAnalystAgent:
    """
    Analyze material startup risks using market evidence, proposed MVP
    scope, and startup-specific RAG context.

    RiskAnalystAgent operates in the full_analysis workflow after the
    MVP recommendation has been generated.

    Risk Categories
    ---------------
    - Market risks
    - Technical risks
    - Execution risks
    - MVP feature-level risks
    - Startup-specific risks
    - Cross-cutting business risks
    - Highest business risk

    Input State
    -----------
    workflow_state["startup_idea"]:
        Startup concept being evaluated.

    workflow_state["startup_type"]:
        Industry/category context.

    workflow_state["market_data"]:
        External market and ecosystem evidence.

    workflow_state["mvp_suggestions"]:
        Proposed MVP features, target users, build scope, and launch
        sequence.

    workflow_state["rag_context"]:
        Relevant startup-specific evidence retrieved from the pitch deck
        or indexed documents.

    Output State
    ------------
    workflow_state["risk_analysis"]:
        Generated structured risk analysis.

    workflow_state["pipeline_status"]["RiskAnalystAgent"]:
        Set to "success" after successful execution.

    Evidence Principle
    ------------------
    Risks must be grounded in the supplied workflow evidence.

    RAG context provides startup-specific information but must not
    automatically be treated as verified fact. Unsupported claims
    should be identified as assumptions requiring validation.

    The agent does not perform independent research. It evaluates
    the evidence already supplied by upstream workflow stages.
    """

    # ============================================================
    # DECORATOR STACK
    # Provides centralized error handling, execution logging,
    # timing measurement, and retry behavior.
    # ============================================================

    @handle_errors
    @log_execution
    @track_timing
    @retry_on_failure
    def run(self, workflow_state: dict) -> dict:
        """
        Analyze material startup risks and update workflow state.

        Parameters
        ----------
        workflow_state : dict
            Shared workflow state containing startup context, market
            research, MVP recommendations, and retrieved RAG evidence.

        Returns
        -------
        dict
            Updated workflow state containing "risk_analysis" and the
            successful RiskAnalystAgent pipeline status.

        Processing Stages
        -----------------
        1. Read startup context.
        2. Read market data and MVP recommendations.
        3. Read and normalize RAG context.
        4. Prepare the risk-analysis system prompt.
        5. Build the evidence-based user prompt.
        6. Combine system and user instructions.
        7. Generate the risk analysis.
        8. Store the generated analysis.
        9. Update pipeline status.
        10. Return the updated workflow state.

        Notes
        -----
        Market data provides external evidence for evaluating market
        and ecosystem-related risks.

        MVP suggestions define the concrete product scope whose
        technical, execution, and business risks are evaluated.

        RAG context provides startup-specific evidence that may expose
        risks arising from pitch-deck assumptions, product requirements,
        target users, business model, technical dependencies, or
        operational plans.

        If no relevant RAG context is available, an explicit fallback
        message is used instead of injecting an empty Python list.
        """

        # ============================================================
        # 1. Read startup context
        # ============================================================

        startup_idea = workflow_state["startup_idea"]

        startup_type = workflow_state["startup_type"]

        # ============================================================
        # 2. Read market data and MVP recommendations
        # ============================================================

        market_data = workflow_state["market_data"]

        mvp_suggestions = workflow_state["mvp_suggestions"]

        # ============================================================
        # 3. Read and normalize RAG context
        # ============================================================

        rag_context = workflow_state.get(
            "rag_context",
            []
        )

        if rag_context:

            rag_context_text = "\n\n".join(
                f"Chunk {index}:\n"
                f"Text: {chunk['text']}\n"
                f"Metadata: {chunk['metadata']}\n"
                f"Relevance Score: {chunk['rerank_score']}"
                + (
                    f"\nRRF Score: {chunk['rrf_score']}"
                    if "rrf_score" in chunk
                    else ""
                )
                for index, chunk in enumerate(
                    rag_context,
                    start=1
                )
            )

        else:

            rag_context_text = (
                "No relevant pitch-deck context available."
            )

        # ============================================================
        # 4. Prepare risk-analysis system prompt
        # ============================================================

        system_prompt = RISK_ANALYST_PROMPT

        # ============================================================
        # 5. Build evidence-based user prompt
        # ============================================================

        user_prompt = f"""
Analyze the startup using the following evidence according to the system instructions.

=== STARTUP IDEA ===
{startup_idea}
=== END STARTUP IDEA ===

=== STARTUP TYPE ===
{startup_type}
=== END STARTUP TYPE ===

=== START MARKET DATA ===
{market_data}
=== END MARKET DATA ===

=== START MVP SUGGESTIONS ===
{mvp_suggestions}
=== END MVP SUGGESTIONS ===

=== START RAG CONTEXT / PITCH DECK ===
{rag_context_text}
=== END RAG CONTEXT / PITCH DECK ===

Use STARTUP IDEA as the primary definition of the startup being evaluated.

Use STARTUP TYPE as the broader industry and category context.

Use MARKET DATA for external market, customer, competitor, trend, and ecosystem evidence.

Use MVP SUGGESTIONS as the concrete product scope whose risks must be evaluated.

Use RAG CONTEXT when it provides relevant startup-specific evidence such as product assumptions, target users, business model, technical dependencies, operational constraints, or pitch-deck claims.

Clearly distinguish evidence-supported risks from assumptions that require validation.

Compare relevant RAG CONTEXT claims against MARKET DATA when both contain relevant information.

Identify material feature-level risks, cross-cutting risks, and the single highest business risk.

Do not invent facts, statistics, competitors, regulations, technical requirements, or URLs.
"""

        # ============================================================
        # 6. Combine system and user instructions
        # ============================================================

        message = (
            system_prompt
            + user_prompt
        )

        # ============================================================
        # 7. Generate risk analysis
        # ============================================================

        risk_analysis_response = text_call(
            user_prompt=message
        )

        # ============================================================
        # 8. Store risk analysis in workflow state
        # ============================================================

        workflow_state["risk_analysis"] = (
            risk_analysis_response
        )

        # ============================================================
        # 9. Update RiskAnalystAgent pipeline status
        # ============================================================

        workflow_state["pipeline_status"]["RiskAnalystAgent"] = (
            "success"
        )

        # ============================================================
        # 10. Return updated workflow state
        # ============================================================

        return workflow_state


# ================================================================
# STANDALONE TEST
# Allows RiskAnalystAgent to be tested independently using the
# shared mock workflow state.
# ================================================================

if __name__ == "__main__":

    # ============================================================
    # 1. Load mock workflow state
    # ============================================================

    from tests.mock_workflow_state import MOCK_STATE_FULL

    workflow_state = MOCK_STATE_FULL.copy()

    # ============================================================
    # 2. Initialize RiskAnalystAgent
    # ============================================================

    agent = RiskAnalystAgent()

    # ============================================================
    # 3. Execute risk analysis pipeline
    # ============================================================

    workflow_state = agent.run(
        workflow_state
    )

    # ============================================================
    # 4. Display generated risk analysis
    # ============================================================

    print(
        workflow_state["risk_analysis"]
    )

    # ============================================================
    # 5. Display execution errors
    # ============================================================

    print("\nERRORS:")

    print(
        workflow_state["errors"]
    )