"""
File        : agents/startup_scorer_agent.py
Triggered By: full_analysis
Tools       : groq_tool.py

Input:
    workflow_state["market_data"]
        External market, customer, competitor, trend, and ecosystem
        evidence produced by upstream research agents.

    workflow_state["web_search_results"]
        Web research findings and externally retrieved evidence.

    workflow_state["rag_context"]
        Relevant startup-specific context retrieved from the pitch
        deck or other indexed documents through the RAG pipeline.

    workflow_state["mvp_suggestions"]
        Proposed MVP features, target users, build scope, and
        launch sequence.

    workflow_state["tech_recommendations"]
        Recommended technology stack and technical rationale.

    workflow_state["risk_analysis"]
        Feature-level, technical, market, execution, and business
        risks identified by the Risk Analyst Agent.

Output:
    workflow_state["startup_score"] → dict
        {
            "score"    : int,       # 0-100 overall viability score
            "reasoning": str,       # LLM-generated explanation
            "breakdown": {
                "market"    : int,  # 0-100
                "mvp"       : int,  # 0-100
                "tech"      : int,  # 0-100
                "risk"      : int   # 0-100 (higher = lower risk)
            },
            "highest_risk_flag": str  # lowest-scoring dimension
        }

Responsibilities:
- Evaluate overall startup viability from 0-100
- Evaluate market strength
- Evaluate MVP quality and feasibility
- Evaluate technical readiness
- Evaluate the overall risk profile
- Use market, web, RAG, MVP, technology, and risk evidence
- Provide per-dimension breakdown scores
- Provide reasoning for the overall assessment
- Identify the weakest / highest-risk dimension
- Validate the LLM-generated JSON structure
- Validate all dimension scores are integers between 0 and 100
- Validate highest_risk_flag identifies a lowest-scoring dimension
- Calculate the final weighted score deterministically
- Store only the validated scoring result in workflow_state
"""

from src.core.decorators import (
    handle_errors,
    log_execution,
    track_timing,
    retry_on_failure
)

from src.prompts.prompts import STARTUP_SCORER_PROMPT
from src.tools.groq_tool import text_call

import json
import re


class StartupScorerAgent:
    """
    Startup Scorer Agent responsible for producing the final quantitative
    viability assessment of the startup using all relevant upstream
    workflow outputs.

    This agent operates near the end of the full_analysis workflow after
    market research, web research, RAG retrieval, MVP analysis,
    technology recommendations, and risk analysis have completed.

    The agent evaluates four scoring dimensions:

        Market:
            Strength of the market opportunity and supporting evidence.

        MVP:
            Quality, relevance, feasibility, and scope of the proposed MVP.

        Tech:
            Suitability and feasibility of the recommended technology stack.

        Risk:
            Overall risk profile, where a higher score represents a
            lower level of startup risk.

    Input State:
        workflow_state["market_data"]:
            External market and ecosystem evidence.

        workflow_state["web_search_results"]:
            Additional web-based research and supporting evidence.

        workflow_state["rag_context"]:
            Startup-specific evidence retrieved from the pitch deck or
            other indexed documents. This context may reveal product,
            business, technical, or operational assumptions that are
            not available in external research.

        workflow_state["mvp_suggestions"]:
            Proposed MVP features, target users, scope, and launch plan.

        workflow_state["tech_recommendations"]:
            Recommended technology stack and technical rationale.

        workflow_state["risk_analysis"]:
            Detailed risk analysis generated by the Risk Analyst Agent.

    Output State:
        workflow_state["startup_score"]:
            Validated startup viability assessment containing the final
            weighted score, LLM reasoning, dimension breakdown, and
            highest-risk dimension.

        workflow_state["pipeline_status"]["StartupScorerAgent"]:
            Updated to "success" when the agent completes successfully.

    Evidence Usage:
        Market data:
            Primary evidence for evaluating market strength and
            opportunity quality.

        Web search results:
            Additional external evidence supporting the startup
            assessment.

        RAG context:
            Startup-specific evidence extracted from the pitch deck
            or indexed documents.

        MVP suggestions:
            Evidence for evaluating product scope, feature quality,
            and MVP feasibility.

        Tech recommendations:
            Evidence for evaluating technical suitability and
            implementation feasibility.

        Risk analysis:
            Evidence for evaluating the startup's overall risk profile.

    Scoring:
        The LLM provides the four dimension scores, reasoning, and
        highest-risk flag.

        The final overall score is calculated deterministically using:

            Market → 30%
            MVP    → 25%
            Tech   → 20%
            Risk   → 25%

    Validation:
        The agent validates that:
            - All required scoring dimensions are present.
            - Every dimension is an integer between 0 and 100.
            - Reasoning is a non-empty string.
            - highest_risk_flag is a valid scoring dimension.
            - highest_risk_flag identifies a dimension whose score equals
              the lowest score.

        The lowest-score comparison allows multiple dimensions to share
        the same lowest score while still accepting any tied dimension
        as the highest-risk flag.

    Notes:
        RAG context is treated as startup-specific supporting evidence
        and is normalized into readable text before being included in
        the LLM prompt.

        If no RAG context is available, the agent supplies an explicit
        fallback message rather than injecting an empty Python list.

        The final weighted score is calculated locally rather than
        trusting the LLM to perform the arithmetic.
    """

    @handle_errors
    @log_execution
    @track_timing
    @retry_on_failure
    def run(self, workflow_state: dict) -> dict:
        """
        Evaluate startup viability using all completed upstream analysis.

        Parameters
        ----------
        workflow_state : dict
            Shared state passed between agents in the multi-agent workflow.

            Required fields:
                "market_data":
                    External market and ecosystem evidence.

                "web_search_results":
                    Web research results.

                "rag_context":
                    Relevant startup-specific context retrieved from the
                    pitch deck or other indexed documents.

                "mvp_suggestions":
                    Proposed MVP features and product scope.

                "tech_recommendations":
                    Recommended technology stack and rationale.

                "risk_analysis":
                    Completed startup risk assessment.

        Returns
        -------
        dict
            Updated workflow state containing the validated startup score
            under "startup_score" and the updated StartupScorerAgent
            execution status.

        Notes
        -----
        RAG context is normalized from retrieved chunk dictionaries into
        a clean text representation before being included in the prompt.

        The LLM is responsible for generating:
            - Market score
            - MVP score
            - Tech score
            - Risk score
            - Reasoning
            - Highest-risk flag

        The agent validates the generated JSON before accepting it.

        The final weighted score is calculated deterministically using
        the validated dimension scores:

            Market → 30%
            MVP    → 25%
            Tech   → 20%
            Risk   → 25%

        The highest-risk flag is valid when its corresponding dimension
        has the lowest score. Ties are allowed because multiple dimensions
        may share the same minimum score.
        """

        # ----------------------------------------------------
        # 1. Read market and web research evidence
        # ----------------------------------------------------

        market_data = workflow_state["market_data"]

        web_search_results = workflow_state["web_search_results"]

        # ----------------------------------------------------
        # 2. Read and normalize RAG context
        # ----------------------------------------------------

        rag_context = workflow_state.get(
            "rag_context",
            []
        )

        if rag_context:

            rag_context_text = "\n\n".join(
                f"Chunk {index}:\n"
                f"Text: {chunk['text']}\n"
                f"Metadata: {chunk['metadata']}\n"
                f"Rerank Score: {chunk['rerank_score']}"
                + (
                    f"\nRRF Score: {chunk['rrf_score']}"
                    if "rrf_score" in chunk
                    else ""
                )
                for index, chunk in enumerate(
                    rag_context,
                    start=1
                )
            )

        else:

            rag_context_text = (
                "No relevant pitch-deck context available."
            )

        # ----------------------------------------------------
        # 3. Read MVP, technology, and risk analysis
        # ----------------------------------------------------

        mvp_suggestions = workflow_state["mvp_suggestions"]

        tech_recommendations = workflow_state["tech_recommendations"]

        risk_analysis = workflow_state["risk_analysis"]

        # ----------------------------------------------------
        # 4. Prepare system prompt
        # ----------------------------------------------------

        system_prompt = STARTUP_SCORER_PROMPT

        # ----------------------------------------------------
        # 5. Build user prompt
        # ----------------------------------------------------

        user_prompt = f"""
Evaluate the startup using the completed upstream analysis below.

=== MARKET DATA ===
{market_data}
=== END MARKET DATA ===

=== WEB SEARCH RESULTS ===
{web_search_results}
=== END WEB SEARCH RESULTS ===

=== RAG CONTEXT / PITCH DECK ===
{rag_context_text}
=== END RAG CONTEXT / PITCH DECK ===

=== MVP SUGGESTIONS ===
{mvp_suggestions}
=== END MVP SUGGESTIONS ===

=== TECH RECOMMENDATIONS ===
{tech_recommendations}
=== END TECH RECOMMENDATIONS ===

=== RISK ANALYSIS ===
{risk_analysis}
=== END RISK ANALYSIS ===

Use only the supplied evidence when evaluating the startup.

Return the required JSON assessment using only the supplied evidence.
"""

        # ----------------------------------------------------
        # 6. Prepare LLM messages
        # ----------------------------------------------------

        messages = [
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_prompt
            }
        ]

        # ----------------------------------------------------
        # 7. Generate startup score assessment
        # ----------------------------------------------------

        response = text_call(
            prompt=messages
        )

        # ----------------------------------------------------
        # 8. Clean accidental Markdown code fences
        # ----------------------------------------------------

        clean_response = re.sub(
            r"^```(?:json)?\s*|\s*```$",
            "",
            response.strip(),
            flags=re.IGNORECASE
        )

        # ----------------------------------------------------
        # 9. Parse LLM JSON response
        # ----------------------------------------------------

        data = json.loads(
            clean_response
        )

        # ----------------------------------------------------
        # 10. Validate LLM-generated breakdown
        # ----------------------------------------------------

        breakdown = data["breakdown"]

        required_dimensions = {
            "market",
            "mvp",
            "tech",
            "risk"
        }

        if set(breakdown.keys()) != required_dimensions:

            raise ValueError(
                "Invalid startup score breakdown dimensions."
            )

        for dimension, value in breakdown.items():

            if (
                isinstance(value, bool)
                or not isinstance(value, int)
            ):

                raise ValueError(
                    f"{dimension} score must be an integer."
                )

            if not 0 <= value <= 100:

                raise ValueError(
                    f"{dimension} score must be between 0 and 100."
                )

        # ----------------------------------------------------
        # 11. Validate reasoning
        # ----------------------------------------------------

        reasoning = data["reasoning"]

        if (
            not isinstance(reasoning, str)
            or not reasoning.strip()
        ):

            raise ValueError(
                "Startup score reasoning must be a non-empty string."
            )

        # ----------------------------------------------------
        # 12. Determine highest-risk / weakest area
        # ----------------------------------------------------

        lowest_score = min(breakdown.values())

        highest_risk_flag = data["highest_risk_flag"]

        if highest_risk_flag not in required_dimensions:
            raise ValueError(
                "Invalid highest_risk_flag."
            )

        if breakdown[highest_risk_flag] != lowest_score:
            raise ValueError(
                "highest_risk_flag must identify a lowest-scoring dimension."
            )

        # ----------------------------------------------------
        # 13. Calculate final score deterministically
        # ----------------------------------------------------

        final_score = round(
            breakdown["market"] * 0.30
            + breakdown["mvp"] * 0.25
            + breakdown["tech"] * 0.20
            + breakdown["risk"] * 0.25
        )

        # ----------------------------------------------------
        # 14. Store startup score in workflow state
        # ----------------------------------------------------

        workflow_state["startup_score"] = {
            "score": final_score,
            "reasoning": reasoning,
            "breakdown": breakdown,
            "highest_risk_flag": highest_risk_flag
        }

        # ----------------------------------------------------
        # 15. Update pipeline status
        # ----------------------------------------------------

        workflow_state["pipeline_status"][
            "StartupScorerAgent"
        ] = "success"

        # ----------------------------------------------------
        # 16. Return updated workflow state
        # ----------------------------------------------------

        return workflow_state


# ----------------------------------------------------
# LOCAL TEST
# ----------------------------------------------------

if __name__ == "__main__":

    # ----------------------------------------------------
    # 1. Load mock workflow state
    # ----------------------------------------------------

    from tests.mock_workflow_state import MOCK_STATE_FULL

    workflow_state = MOCK_STATE_FULL.copy()

    # ----------------------------------------------------
    # 2. Initialize Startup Scorer Agent
    # ----------------------------------------------------

    agent = StartupScorerAgent()

    # ----------------------------------------------------
    # 3. Run startup scoring pipeline
    # ----------------------------------------------------

    workflow_state = agent.run(
        workflow_state
    )

    # ----------------------------------------------------
    # 4. Print generated startup score
    # ----------------------------------------------------

    print(
        workflow_state["startup_score"]
    )